### ISSUE TITLE
Linking Firebase Database fails for Carthage binary 5.18.1 and other versions not available for download.

### ISSUE THREAD

**Issue by acrookston** [firebase/firebase-ios-sdk#2493]
**This is completely breaking build pipelines using Carthage.**

### [READ] Step 1: Are you in the right place?

✅ 

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.1 (10B61)
  * Firebase SDK version: 5.18.1
  * Firebase Component: Database, Analytics, Auth, Performance
  * Component version: 5.18.1

### [REQUIRED] Step 3: Describe the problem

While archiving an app (via fastlane) for test flight upload carthage bootstrap failed when attempting to download 5.16.0. The binary json file at xxxx indicates that there is no 5.16.0 available and only available option is 5.18.1.

After updating the Carthage dependency to 5.18.1, Carthage bootstrap succeeds but when xcode enters linking phase it fails with the following error:

```
[17:19:31]: ▸ Undefined symbols for architecture arm64:
[17:19:31]: ▸   "_utf8_nextCharSafeBody", referenced from:
[17:19:31]: ▸       -[FSRWebSocket _innerPumpScanner] in FirebaseDatabase(FSRWebSocket.o)
[17:19:31]: ▸ ld: symbol(s) not found for architecture arm64
[17:19:31]: ▸ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`Cartfile` fails fetching 5.16.0:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 5.16.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" == 5.16.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json" == 5.16.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" == 5.16.0
```

Carthage bootstrap succeeds but linking faills with `Cartfile`:
```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 5.18.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAuthBinary.json" == 5.18.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseDatabaseBinary.json" == 5.18.1
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" == 5.18.1
```

NOTE: I am seeing this issue when building via fastlane and in Xcode.

#### Steps to reproduce:

Using Carthage in an application, update binary definitions according to above in `Cartfile`.
Build and run the application in Xcode or via fastlane scripts (same result).
See linking error above.

#### Relevant Code:

Cartfile definitions above.

**Comment by ryanwilson** [comment]
@acrookston Sorry for the issues, the incorrect Carthage files were pushed during our latest release. We're looking into it right now and hope to have it resolved very shortly.

**Comment by paulb777** [comment]
Does https://stackoverflow.com/questions/35370611/getting-utf8-nextcharsafebody-error help with the 5.18.1 linker issue?

**Comment by acrookston** [comment]
@paulb777 I'm attempting to build with that now.

**Comment by ryanwilson** [comment]
We've identified the issue and are working on getting it fixed and published ASAP. I'll update this bug when it's back.

**Comment by acrookston** [comment]
Confirming that the suggested fix worked on my app. Thanks for quick response and resolve.

**Comment by ryanwilson** [comment]
@acrookston happy to hear you're unblocked - sorry for the troubles and thank you very much for reporting this! Currently validating the proposed fix.

**Comment by ryanwilson** [comment]
@acrookston the release is live with version `5.18.2`. Can you please confirm that the fix works for you? The old versions should be available now as well. I'll close the issue but please re-open it if something is still broken.
