### PR TITLE
Update travis to use CocoaPods 1.5.0

### PR DESCRIPTION
**Pull request by paulb777**

### CODE REVIEW

**Comment by paulb777** [comment]
ios and tvOS tests failing with 

2018-04-14 15:03:20.671 xcodebuild[7023:18568]  iOSSimulator: task_name_for_pid(mach_task_self(), 8340, &task) returned 5
2018-04-14 15:03:20.675 xcodebuild[7023:18568]  iOSSimulator: Falling back to DISPATCH_SOURCE_TYPE_PROC
2018-04-14 15:03:21.075 xcodebuild[7023:14859] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
2018-04-14 15:03:21.076 xcodebuild[7023:14859] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
2018-04-14 15:03:21.076 xcodebuild[7023:14859] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
2018-04-14 15:03:21.076 xcodebuild[7023:14859] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

**Comment by wilhuff** [comment]
@paulb777, is this in a reviewable state? Your comments here indicate this isn't working.

**Comment by paulb777** [comment]
Adding CODE_SIGNING_ALLOWED=YES to the Firebase builds gets them to go, but it looks like there's another issue with the Firestore builds that it can't find FirebaseAuth.

**Comment by paulb777** [comment]
Seem to be getting close - but for some reason the reorganized build causes 21 Firestore unit test failures ....


FSTLocalSerializerTests
  testEncodesMutationBatch, (([self.serializer encodedMutationBatch:model]) equal to (batchProto)) failed: ("<FSTPBWriteBatch 0x608000203820>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm:123
  ```
  XCTAssertEqualObjects([self.serializer encodedMutationBatch:model], batchProto);
  FSTMutationBatch *decoded = [self.serializer decodedMutationBatch:batchProto];
  ```
  testEncodesQueryData, (([self.serializer encodedQueryData:queryData]) equal to (expected)) failed: ("<FSTPBTarget 0x60c0000d9240>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm:186
  ```
  XCTAssertEqualObjects([self.serializer encodedQueryData:queryData], expected);
  FSTQueryData *decoded = [self.serializer decodedQueryData:expected];
  ```
FSTSerializerBetaTests
  testEncodesArrayContainsFilter, ((actual) equal to (expected)) failed: ("<GCFSStructuredQuery_Filter 0x60b000030c90>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:499
  ```
  prop.value.stringValue = @"food";
  XCTAssertEqualObjects(actual, expected);
}
  ```
  testEncodesArrays, ((actualProto) equal to (value)) failed: ("<GCFSValue 0x60e0000d92e0>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:335
  ```
  XCTAssertEqual(actualProto.valueTypeOneOfCase, type);
  XCTAssertEqualObjects(actualProto, value);
  ```
  testEncodesArrayTransformMutations, ((actualProto) equal to (proto)) failed: ("<GCFSWrite 0x60c000212a40>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:435
  ```
  GCFSWrite *actualProto = [self.serializer encodedMutation:mutation];
  XCTAssertEqualObjects(actualProto, proto);
  ```
  testEncodesFirstLevelAncestorQueries, ((actualProto) equal to (proto)) failed: ("<GCFSTarget 0x60c000138700>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:739
  ```
  GCFSTarget *actualProto = [self.serializer encodedTarget:queryData];
  XCTAssertEqualObjects(actualProto, proto);
  ```
  testEncodesFirstLevelKeyQueries, ((actualProto) equal to (proto)) failed: ("<GCFSTarget 0x60c00015ed40>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:739
  ```
  GCFSTarget *actualProto = [self.serializer encodedTarget:queryData];
  XCTAssertEqualObjects(actualProto, proto);
  ```
  testEncodesLimits, ((actualProto) equal to (proto)) failed: ("<GCFSTarget 0x60c0001d2480>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:739
  ```
  GCFSTarget *actualProto = [self.serializer encodedTarget:queryData];
  XCTAssertEqualObjects(actualProto, proto);
  ```
  testEncodesMultipleFiltersOnDeeperCollections, ((actualProto) equal to (proto)) failed: ("<GCFSTarget 0x60c0000cfe80>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:739
  ```
  GCFSTarget *actualProto = [self.serializer encodedTarget:queryData];
  XCTAssertEqualObjects(actualProto, proto);
  ```
  testEncodesNanFilter, ((actualProto) equal to (proto)) failed: ("<GCFSTarget 0x60c00000c040>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:739
  ```
  GCFSTarget *actualProto = [self.serializer encodedTarget:queryData];
  XCTAssertEqualObjects(actualProto, proto);
  ```
  testEncodesNestedAncestorQueries, ((actualProto) equal to (proto)) failed: ("<GCFSTarget 0x60c00000c640>: {
  /Users/travis/build/firebase/firebase-ios-sdk/Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm:739
  ```
  GCFSTarget *actualProto = [self.serializer encodedTarget:queryData];
  XCTAssertEqualObjects(actualProto, proto);
  ```

**Comment by paulb777** [comment]
Now ready for review.  Read the updated description at top for a summary.

File: Firestore/Example/Podfile [hunk 1]
```diff
@@ -10,63 +10,32 @@ pod 'Firebase/Core', '5.0.0'
...
-pod 'FirebaseCore', :path => '../../'
-pod 'FirebaseFirestore', :path => '../../'
-
 target 'Firestore_Example_iOS' do
   platform :ios, '8.0'
 
-  # Test targets are below to avoid problems with duplicate symbols when
-  # building as a static library (see comments below).
-end
+  pod 'FirebaseAuth', :path => '../../'
```
Comment (wilhuff) [inline Firestore/Example/Podfile]: Did you intend to re-nest these here or is this just a bad merge? How does this work around all the duplicate class warnings we were getting from linking the framework into the example app?

Comment (paulb777) [reply Firestore/Example/Podfile]: I don't intend to re-nest them. They ONLY get linked into the example app. I added -force_load to the Example app build `OTHER_LDFLAGS` so that unused C++ functions get linked in. Then the test target doesn't need them to build and finds them at runtime from the app.

File: Firestore/Example/Firestore.xcodeproj/project.pbxproj [hunk 2]
```diff
@@ -1864,6 +1533,10 @@
 				);
 				INFOPLIST_FILE = "Firestore/Firestore-Info.plist";
 				MODULE_NAME = ExampleApp;
+				OTHER_LDFLAGS = (
```
Comment (paulb777) [inline Firestore/Example/Firestore.xcodeproj/project.pbxproj]: This is the relevant change not from `pod deprecate`

Comment (wilhuff) [reply Firestore/Example/Firestore.xcodeproj/project.pbxproj]: `pod deprecate` doesn't seem to be a thing. Do you mean `pod deintegrate`?

I'm not sure we're seeing much pain from having the project stored integrated. It does mean that as developers we need to run the same version of cocoapods, but that's pretty easy for us to coordinate within the Firestore team.

Meanwhile as we're migrating to C++ we're constantly changing the project to add C++ tests and remove Objective-C tests. It will be a serious pain to have to `pod deintegrate` to even be able to read the diffs of those changes.

I get it that `pod deintegrate`d projects are cleaner, but practically speaking they're much more cumbersome. I think we should leave this installed.

Comment (paulb777) [reply Firestore/Example/Firestore.xcodeproj/project.pbxproj]: Yes I meant `pod deintegrate`.  And undone now.
