### ISSUE TITLE
Firebase ML Interpreter, link error since upgrading from 5.16.0 to 6.6.0

### ISSUE THREAD

**Issue by NicolasVidal** [firebase/firebase-ios-sdk#4000]
### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.6.0
  * Firebase Component: ML Interpreter
  * Component version: 6.6.0

### [REQUIRED] Step 3: Describe the problem
We were using Firebase ML Interpreter in version 5.16.0 and everything was working fine. We had to upgrade to Firebase 6.6.0 due to another dependency compatibility issue.

Since we upgraded the version in the PodFile, we can't build our project anymore.

#### Steps to reproduce:
When we try to build our project we get the following error : 

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FBMLx_GPBInt32Array", referenced from:
      objc-class-ref in FirebaseMLModelInterpreter(FIRModelDataSpec_ad36d8db163cab262491d723480a8e00.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

:-1: Undefined symbol: _OBJC_CLASS_$_FBMLx_GPBInt32Array

#### Relevant Code:

A Piece of our PodFile :
```
  pod 'Firebase', '6.6.0'
  pod 'Firebase/Analytics', '6.6.0'
  pod 'Firebase/Auth', '6.6.0'
  pod 'Firebase/Messaging', '6.6.0'
  pod 'Firebase/RemoteConfig', '6.6.0'
  pod 'Firebase/MLModelInterpreter', '6.6.0'
```

**Comment by morganchen12** [comment]
@NicolasVidal is this still an issue on 6.9.0? I'm not able to reproduce the issue with the ML Kit samples.

**Comment by NicolasVidal** [comment]
@morganchen12 This is indeed not an issue with 6.9.0, and right now just for iOS we are using it. But the issue is that the Firebase Unity SDK we are using is still in 6.6.0 (https://firebase.google.com/download/unity), we hope that using 6.6.0 unity wrapper with 6.9.0 won't cause any issue with the rest of Firebase services, but it's not a perfect solution.

**Comment by paulb777** [comment]
Closing here. Please open an issue at https://github.com/firebase/quickstart-unity/issues for additional assistance.
