### ISSUE TITLE
Fix FirebaseCore test failures with OCMock 3.5.0

### ISSUE THREAD

**Issue by paulb777** [firebase/firebase-ios-sdk#4343]
From https://travis-ci.org/firebase/firebase-ios-sdk/jobs/613701568:

https://console.firebase.googl/Users/travis/build/firebase/firebase-ios-sdk/Example/Core/Tests/FIRComponentContainerTest.m:81: error:
-[FIRComponentContainerTest testComponentsPopulatedOnInit] : failed: caught "NSInternalInconsistencyException", "Mock object was not used in OCMStub/OCMExpect/OCMReject. Did you accidentally use a real object?"

**Comment by morganchen12** [comment]
Caused by https://github.com/erikdoe/ocmock/commit/40d3e22f29c20d1bb54e8b4f79aab55225cc4b72
