### PR TITLE
test(auth): enable SPM unit tests for PhoneAuthProvider and AuthNotificationManager

### PR DESCRIPTION
**Pull request by paulb777**
This PR addresses a TODO in Package.swift by enabling PhoneAuthProviderTests and AuthNotificationManagerTests for Swift Package Manager.

### Changes:
* Removed PhoneAuthProviderTests.swift and AuthNotificationManagerTests.swift from the exclude list in Package.swift.
* Explicitly injects fakes for appCredentialManager, notificationManager, and tokenManager in PhoneAuthProviderTests.initApp() to fix test timeouts and build errors caused by Missing host applications in SPM environments.
* Added missing `@unchecked Sendable` conformance to AuthNotificationManager and FakeNotificationManager to resolve compilation errors.
* Made FakeApplication conform to AuthAPNSTokenApplication and marked its `delegate` property as `weak` to prevent retain cycles in tests.
* Added thread safety to AuthNotificationManager by protecting its mutable state with an `NSLock` and a custom synchronous helper to ensure compatibility across Swift 6 concurrency and older deployment targets (iOS 15 / macOS 10.15).

### CODE REVIEW

**Comment by paulb777** [comment]
The failed tests are unrelated and addressed in #16452

**Review by ncooke3 — APPROVED** [review]
