### ISSUE TITLE
Build fail on FirebaseSessions after Updating to 10.22.0

### ISSUE THREAD

**Issue by Taehyeong-Jo** [firebase/firebase-ios-sdk#12478]
### Description

Build is failing with the below errors 

It was fine until 10.21.0, but starting from 10.22.0.

<br>

<img width="449" alt="Screenshot 2024-03-06 at 5 53 40 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/127076141/e5a90478-9daa-4c1f-a7a4-46cbb916a75f">

<br>

<br>

<br>

**- Cannot find type 'Library' in scope**

<img width="1396" alt="Screenshot 2024-03-06 at 5 54 37 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/127076141/77c9165c-9834-4cca-97be-154ccae01b13">

<br>
<br>
<br>

**- Cannot find 'FirebaseVersion' in scope**

<img width="1386" alt="Screenshot 2024-03-06 at 5 54 45 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/127076141/18803f04-fe6a-4325-b03c-96824040eeff">

<br>
<br>
<br>

**-  Cannot find type 'Component' in scope**

<img width="1391" alt="Screenshot 2024-03-06 at 5 54 50 PM" src="https://github.com/firebase/firebase-ios-sdk/assets/127076141/40c5e2f7-04d2-47e2-8b61-11e76db288e0">

<br>
<br>
<br>

### Reproducing the issue

Use the latest firebase version (10.22.0) and update the SPM by tuist

### Firebase SDK Version

10.22.0

### Xcode Version

15.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Crashlytics, DynamicLinks, Messaging

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

{
  "originHash" : "c213697761692867914c93dfb964cc7abcd1ded282a53fdfcceea69d3c305ef2",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bfc0b6f81adc06ce5121eb23f628473638d67c5c",
        "version" : "1.2022062300.0"
      }
    },
    {
      "identity" : "addwith",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/euisuk-lee/AddWith",
      "state" : {
        "revision" : "f11a063e6362c428aca3aa3f9fbb1606077fef4b",
        "version" : "1.1.4"
      }
    },
    {
      "identity" : "alamofire",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Alamofire/Alamofire",
      "state" : {
        "revision" : "b2fa556e4e48cbf06cf8c63def138c98f4b811fa",
        "version" : "5.8.0"
      }
    },
    {
      "identity" : "amplitude-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/amplitude/Amplitude-iOS",
      "state" : {
        "revision" : "dca2c744336e651ee285011282b86accc2ce3704",
        "version" : "8.17.2"
      }
    },
    {
      "identity" : "analytics-connector-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/amplitude/analytics-connector-ios.git",
      "state" : {
        "revision" : "b44981119e2efc0edd1d2e26831c3c4c0e0264e6",
        "version" : "1.0.0"
      }
    },
    {
      "identity" : "anycodable",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Flight-School/AnyCodable.git",
      "state" : {
        "revision" : "862808b2070cd908cb04f9aafe7de83d35f81b05",
        "version" : "0.6.7"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "5746b2d35c91c50581590ed97abe4c06b5037274",
        "version" : "10.18.0"
      }
    },
    {
      "identity" : "bonmot",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Rightpoint/BonMot",
      "state" : {
        "revision" : "2df34a28c97e2413c44a7be70b6dd15adf783baf",
        "version" : "6.1.1"
      }
    },
    {
      "identity" : "cgfloatliteral",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/devxoul/CGFloatLiteral",
      "state" : {
        "revision" : "05a4533a90291ac152c67caa5a81be50d733bae7",
        "version" : "0.5.0"
      }
    },
    {
      "identity" : "combinecocoa",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/CombineCommunity/CombineCocoa.git",
      "state" : {
        "revision" : "7300c75ff9e072aa7fd0fccefcc88f74aae9bf56",
        "version" : "0.4.1"
      }
    },
    {
      "identity" : "facebook-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/facebook/facebook-ios-sdk",
      "state" : {
        "revision" : "5ed7a05695b2830fcfd97b62225272fad2f61043",
        "version" : "16.1.3"
      }
    },
    {
      "identity" : "factory",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/hmlongco/Factory.git",
      "state" : {
        "revision" : "8ca11a7bd1ede031e8e6d7a912bb116e2e43961b",
        "version" : "2.3.1"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk",
      "state" : {
        "revision" : "fe09d61a539e11fdbe24f269bba10144b6145fe2",
        "version" : "10.22.0"
      }
    },
    {
      "identity" : "floatingpanel",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/scenee/FloatingPanel",
      "state" : {
        "revision" : "b00a05b9ed7717da0e5ce1b760e27ffcbaddd333",
        "version" : "2.5.4"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "bf3bb24f6b60a7acedaef504e9ce97154203217a",
        "version" : "10.22.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "a732a4b47f59e4f725a2ea10f0c77e93a7131117",
        "version" : "9.3.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "bc27fad73504f3d4af235de451f02ee22586ebd3",
        "version" : "7.12.1"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "a673bc2937fbe886dd1f99c401b01b6d977a9c98",
        "version" : "1.49.1"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "d4289da23e978f37c344ea6a386e5546e2466294",
        "version" : "2.1.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "2d12673670417654f08f5f90fdd62926dc3a2648",
        "version" : "100.0.0"
      }
    },
    {
      "identity" : "ios-branch-sdk-spm",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/BranchMetrics/ios-branch-sdk-spm",
      "state" : {
        "revision" : "65dcd12e0107e1e1c464fabcd0ba29c577648650",
        "version" : "1.45.2"
      }
    },
    {
      "identity" : "kakao-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/kakao/kakao-ios-sdk",
      "state" : {
        "revision" : "9f3a186d10619ff14e08ae8e44a59919624abe8b",
        "version" : "2.17.0"
      }
    },
    {
      "identity" : "kakaoadpackage",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/KakaoAd/KakaoAdPackage",
      "state" : {
        "revision" : "597f3be0efdf32f5d4c65d0d3dcb96f76b74a7a3",
        "version" : "0.7.2"
      }
    },
    {
      "identity" : "keychainaccess",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/kishikawakatsumi/KeychainAccess",
      "state" : {
        "revision" : "84e546727d66f1adc5439debad16270d0fdd04e7",
        "version" : "4.2.2"
      }
    },
    {
      "identity" : "kingfisher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/onevcat/Kingfisher",
      "state" : {
        "revision" : "b6f62758f21a8c03cd64f4009c037cfa580a256e",
        "version" : "7.9.1"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "0706abcc6b0bd9cedfbb015ba840e4a780b5159b",
        "version" : "1.22.2"
      }
    },
    {
      "identity" : "logger",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/nilotic/Logger",
      "state" : {
        "revision" : "24063af4e6228eb4d10b009c92695edfbc4342e0",
        "version" : "1.1.5"
      }
    },
    {
      "identity" : "lottie-ios",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/airbnb/lottie-ios",
      "state" : {
        "revision" : "f522990668c2f9132323a2e68d924c7dcb9130b4",
        "version" : "4.4.0"
      }
    },
    {
      "identity" : "marqueelabel",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/cbpowell/MarqueeLabel",
      "state" : {
        "revision" : "f2c72a5f8568579dade6350dc26a482076d3d346",
        "version" : "4.3.0"
      }
    },
    {
      "identity" : "moya",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Moya/Moya",
      "state" : {
        "revision" : "c263811c1f3dbf002be9bd83107f7cdc38992b26",
        "version" : "15.0.3"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "819d0a2173aff699fb8c364b6fb906f7cdb1a692",
        "version" : "2.30909.0"
      }
    },
    {
      "identity" : "notificationbanner",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/Daltron/NotificationBanner",
      "state" : {
        "revision" : "e856a462053daf80c7936056d64246983f3f4d14",
        "version" : "3.1.0"
      }
    },
    {
      "identity" : "pinlayout",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/layoutBox/PinLayout",
      "state" : {
        "revision" : "75c88c5c374c7bc78a154ffdf963cd362f38258a",
        "version" : "1.10.3"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "e70e889c0196c76d22759eb50d6a0270ca9f1d9e",
        "version" : "2.3.1"
      }
    },
    {
      "identity" : "reactiveswift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ReactiveCocoa/ReactiveSwift.git",
      "state" : {
        "revision" : "c43bae3dac73fdd3cb906bd5a1914686ca71ed3c",
        "version" : "6.7.0"
      }
    },
    {
      "identity" : "reactorkit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ReactorKit/ReactorKit",
      "state" : {
        "revision" : "8fa33f09c6f6621a2aa536d739956d53b84dd139",
        "version" : "3.2.0"
      }
    },
    {
      "identity" : "reusablekit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/euisuk-lee/ReusableKit",
      "state" : {
        "revision" : "230fc110da1c70d77d37140fd44437abd3418121",
        "version" : "3.1.0"
      }
    },
    {
      "identity" : "rxdatasources",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RxSwiftCommunity/RxDataSources",
      "state" : {
        "revision" : "90c29b48b628479097fe775ed1966d75ac374518",
        "version" : "5.0.2"
      }
    },
    {
      "identity" : "rxgesture",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RxSwiftCommunity/RxGesture",
      "state" : {
        "revision" : "1b137c576b4aaaab949235752278956697c9e4a0",
        "version" : "4.0.4"
      }
    },
    {
      "identity" : "rxkeyboard",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RxSwiftCommunity/RxKeyboard",
      "state" : {
        "revision" : "085fd99d7bb4f98e671904fcfe7ff561e66574ad",
        "version" : "2.0.0"
      }
    },
    {
      "identity" : "rxoptional",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/RxSwiftCommunity/RxOptional",
      "state" : {
        "revision" : "10820dd92601e8cf7b71c763fc7a1cf4d1bb14f5",
        "version" : "5.0.5"
      }
    },
    {
      "identity" : "rxswift",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ReactiveX/RxSwift",
      "state" : {
        "revision" : "b4307ba0b6425c0ba4178e138799946c3da594f8",
        "version" : "6.5.0"
      }
    },
    {
      "identity" : "rxviewcontroller",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/euisuk-lee/RxViewController",
      "state" : {
        "revision" : "abda29d18812653f44088fd4463ce8a90bc6acc8",
        "version" : "2.0.2"
      }
    },
    {
      "identity" : "snapkit",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SnapKit/SnapKit",
      "state" : {
        "revision" : "f222cbdf325885926566172f6f5f06af95473158",
        "version" : "5.6.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "b8230909dedc640294d7324d37f4c91ad3dcf177",
        "version" : "1.20.1"
      }
    },
    {
      "identity" : "swift-syntax",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-syntax.git",
      "state" : {
        "revision" : "43c802fb7f96e090dde015344a94b5e85779eff1",
        "version" : "509.1.0"
      }
    },
    {
      "identity" : "swiftdate",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/malcommac/SwiftDate",
      "state" : {
        "revision" : "6190d0cefff3013e77ed567e6b074f324e5c5bf5",
        "version" : "6.3.1"
      }
    },
    {
      "identity" : "swiftyjson",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/SwiftyJSON/SwiftyJSON",
      "state" : {
        "revision" : "2b6054efa051565954e1d2b9da831680026cd768",
        "version" : "4.3.0"
      }
    },
    {
      "identity" : "then",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/devxoul/Then",
      "state" : {
        "revision" : "d41ef523faef0f911369f79c0b96815d9dbb6d7a",
        "version" : "3.0.0"
      }
    },
    {
      "identity" : "tlphotopicker",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/tilltue/TLPhotoPicker",
      "state" : {
        "revision" : "0d0cbbd2d20ed5fd36e5f4052209f5e2d9aaa8b7",
        "version" : "2.1.9"
      }
    },
    {
      "identity" : "uitextview-placeholder",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/easi6dev/UITextView-Placeholder",
      "state" : {
        "revision" : "38bd121b8612fc0ee776990d7c3ce09b0e9082a8",
        "version" : "1.4.1"
      }
    },
    {
      "identity" : "urlnavigator",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/devxoul/URLNavigator",
      "state" : {
        "revision" : "18ba61fd8022191c1be47b1ce845b7daa94a2924",
        "version" : "2.4.1"
      }
    },
    {
      "identity" : "weakmaptable",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/ReactorKit/WeakMapTable.git",
      "state" : {
        "revision" : "cb05d64cef2bbf51e85c53adee937df46540a74e",
        "version" : "1.2.1"
      }
    }
  ],
  "version" : 3
}


```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
Please make sure you're using at least Tuist 4.4. See https://github.com/tuist/tuist/issues/6036#issuecomment-1980849357

**Comment by Taehyeong-Jo** [comment]
Thank you for your support 👍
