### ISSUE TITLE
_OBJC_CLASS_$_FIRAnalytics symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by skajake** [firebase/firebase-ios-sdk#7614]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _12.3_
  * Firebase SDK version: _7.X_
  * Installation method: `CocoaPods`
  * Firebase Component: _Core_

### [REQUIRED] Step 2: Describe the problem

When upgrading Firebase from 6.X to 7.X, and when targeting simulator, I get the following linker error:

```
 "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in MainTabBarController.o
ld: symbol(s) not found for architecture x86_64
```

I do not get this error when targeting a device and it does not happen if I downgrade back to 6.X

**Comment by paulb777** [comment]
It might be necessary to run `pod deintegrate` before `pod install` or `pod update` when switching between 6.x and 7.4+

**Comment by skajake** [comment]
I ran the following steps:
Close xcode and delete derived data
`pod deintegrate`
`pod update` (this updated to 7.7.0)
Reopened the workspace and build.

Same error:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in MainTabBarController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by paulb777** [comment]
@skajake Sorry that didn't help. Please share the Podfile and generated Podfile.lock. Are you able to successfully build the [Firebase Analytics Quick Start](https://github.com/firebase/quickstart-ios/tree/master/analytics)?  If so, there may be an Settings problem in the Xcode project.

**Comment by skajake** [comment]
If I create a new project it works fine, so its definitely some issue with the project.  

Podfile:

```
 platform :ios, '11.0'
 plugin 'cocoapods-patch'

target 'Project Name' do
   use_frameworks!

  pod 'RMStore', :git => 'https://github.com/robotmedia/RMStore.git'
  pod 'RMStore/KeychainPersistence', :git => 'https://github.com/robotmedia/RMStore.git'
  pod 'Appirater'
  pod 'DZNEmptyDataSet', :git => 'https://github.com/skajake/DZNEmptyDataSet.git'
  pod 'UIViewController+BackButtonHandler', :git => 'https://github.com/onegray/UIViewController-BackButtonHandler.git'
  pod 'Firebase/Core'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'EDSunriseSet'
  pod 'Siesta', '~> 1.0'
  pod 'Atributika'
  pod 'CocoaLumberjack'
  pod 'FairBidSDK'
  pod 'Google-Mobile-Ads-SDK'
  pod 'FBAudienceNetwork'
  pod 'AdColony'
  pod 'AppLovinSDK'
  pod 'InMobiSDK'
  pod 'IronSourceSDK'
  pod 'UnityAds'
  pod 'StreamingKit'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
              config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
          end
      end
  end
  
end

```
Podfile.lock:

```
PODS:
  - abseil/algorithm (0.20200225.0):
    - abseil/algorithm/algorithm (= 0.20200225.0)
    - abseil/algorithm/container (= 0.20200225.0)
  - abseil/algorithm/algorithm (0.20200225.0):
    - abseil/base/config
  - abseil/algorithm/container (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/base (0.20200225.0):
    - abseil/base/atomic_hook (= 0.20200225.0)
    - abseil/base/base (= 0.20200225.0)
    - abseil/base/base_internal (= 0.20200225.0)
    - abseil/base/bits (= 0.20200225.0)
    - abseil/base/config (= 0.20200225.0)
    - abseil/base/core_headers (= 0.20200225.0)
    - abseil/base/dynamic_annotations (= 0.20200225.0)
    - abseil/base/endian (= 0.20200225.0)
    - abseil/base/errno_saver (= 0.20200225.0)
    - abseil/base/exponential_biased (= 0.20200225.0)
    - abseil/base/log_severity (= 0.20200225.0)
    - abseil/base/malloc_internal (= 0.20200225.0)
    - abseil/base/periodic_sampler (= 0.20200225.0)
    - abseil/base/pretty_function (= 0.20200225.0)
    - abseil/base/raw_logging_internal (= 0.20200225.0)
    - abseil/base/spinlock_wait (= 0.20200225.0)
    - abseil/base/throw_delegate (= 0.20200225.0)
  - abseil/base/atomic_hook (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/base (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/log_severity
    - abseil/base/raw_logging_internal
    - abseil/base/spinlock_wait
    - abseil/meta/type_traits
  - abseil/base/base_internal (0.20200225.0):
    - abseil/base/config
    - abseil/meta/type_traits
  - abseil/base/bits (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/config (0.20200225.0)
  - abseil/base/core_headers (0.20200225.0):
    - abseil/base/config
  - abseil/base/dynamic_annotations (0.20200225.0)
  - abseil/base/endian (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/errno_saver (0.20200225.0):
    - abseil/base/config
  - abseil/base/exponential_biased (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/log_severity (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/base/malloc_internal (0.20200225.0):
    - abseil/base/base
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/dynamic_annotations
    - abseil/base/raw_logging_internal
  - abseil/base/periodic_sampler (0.20200225.0):
    - abseil/base/core_headers
    - abseil/base/exponential_biased
  - abseil/base/pretty_function (0.20200225.0)
  - abseil/base/raw_logging_internal (0.20200225.0):
    - abseil/base/atomic_hook
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/log_severity
  - abseil/base/spinlock_wait (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/core_headers
    - abseil/base/errno_saver
  - abseil/base/throw_delegate (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/container/compressed_tuple (0.20200225.0):
    - abseil/utility/utility
  - abseil/container/inlined_vector (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/container/inlined_vector_internal
    - abseil/memory/memory
  - abseil/container/inlined_vector_internal (0.20200225.0):
    - abseil/base/core_headers
    - abseil/container/compressed_tuple
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/span
  - abseil/memory (0.20200225.0):
    - abseil/memory/memory (= 0.20200225.0)
  - abseil/memory/memory (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/meta (0.20200225.0):
    - abseil/meta/type_traits (= 0.20200225.0)
  - abseil/meta/type_traits (0.20200225.0):
    - abseil/base/config
  - abseil/numeric/int128 (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
  - abseil/strings/internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/meta/type_traits
  - abseil/strings/str_format (0.20200225.0):
    - abseil/strings/str_format_internal
  - abseil/strings/str_format_internal (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/types/span
  - abseil/strings/strings (0.20200225.0):
    - abseil/base/base
    - abseil/base/bits
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/base/endian
    - abseil/base/raw_logging_internal
    - abseil/base/throw_delegate
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/numeric/int128
    - abseil/strings/internal
  - abseil/time (0.20200225.0):
    - abseil/time/internal (= 0.20200225.0)
    - abseil/time/time (= 0.20200225.0)
  - abseil/time/internal (0.20200225.0):
    - abseil/time/internal/cctz (= 0.20200225.0)
  - abseil/time/internal/cctz (0.20200225.0):
    - abseil/time/internal/cctz/civil_time (= 0.20200225.0)
    - abseil/time/internal/cctz/time_zone (= 0.20200225.0)
  - abseil/time/internal/cctz/civil_time (0.20200225.0):
    - abseil/base/config
  - abseil/time/internal/cctz/time_zone (0.20200225.0):
    - abseil/base/config
    - abseil/time/internal/cctz/civil_time
  - abseil/time/time (0.20200225.0):
    - abseil/base/base
    - abseil/base/core_headers
    - abseil/base/raw_logging_internal
    - abseil/numeric/int128
    - abseil/strings/strings
    - abseil/time/internal/cctz/civil_time
    - abseil/time/internal/cctz/time_zone
  - abseil/types (0.20200225.0):
    - abseil/types/any (= 0.20200225.0)
    - abseil/types/bad_any_cast (= 0.20200225.0)
    - abseil/types/bad_any_cast_impl (= 0.20200225.0)
    - abseil/types/bad_optional_access (= 0.20200225.0)
    - abseil/types/bad_variant_access (= 0.20200225.0)
    - abseil/types/compare (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - abseil/types/span (= 0.20200225.0)
    - abseil/types/variant (= 0.20200225.0)
  - abseil/types/any (0.20200225.0):
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_any_cast
    - abseil/utility/utility
  - abseil/types/bad_any_cast (0.20200225.0):
    - abseil/base/config
    - abseil/types/bad_any_cast_impl
  - abseil/types/bad_any_cast_impl (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_optional_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/bad_variant_access (0.20200225.0):
    - abseil/base/config
    - abseil/base/raw_logging_internal
  - abseil/types/compare (0.20200225.0):
    - abseil/base/core_headers
    - abseil/meta/type_traits
  - abseil/types/optional (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/memory/memory
    - abseil/meta/type_traits
    - abseil/types/bad_optional_access
    - abseil/utility/utility
  - abseil/types/span (0.20200225.0):
    - abseil/algorithm/algorithm
    - abseil/base/core_headers
    - abseil/base/throw_delegate
    - abseil/meta/type_traits
  - abseil/types/variant (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/base/core_headers
    - abseil/meta/type_traits
    - abseil/types/bad_variant_access
    - abseil/utility/utility
  - abseil/utility/utility (0.20200225.0):
    - abseil/base/base_internal
    - abseil/base/config
    - abseil/meta/type_traits
  - AdColony (4.5.0)
  - Appirater (2.3.1)
  - AppLovinSDK (6.15.2)
  - Atributika (4.9.10)
  - BoringSSL-GRPC (0.0.7):
    - BoringSSL-GRPC/Implementation (= 0.0.7)
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Implementation (0.0.7):
    - BoringSSL-GRPC/Interface (= 0.0.7)
  - BoringSSL-GRPC/Interface (0.0.7)
  - CocoaLumberjack (3.7.0):
    - CocoaLumberjack/Core (= 3.7.0)
  - CocoaLumberjack/Core (3.7.0)
  - DZNEmptyDataSet (1.8.1)
  - EDSunriseSet (1.0)
  - FairBidSDK (3.12.0)
  - FBAudienceNetwork (6.3.0):
    - FBSDKCoreKit/Basics (>= 7.0.1)
  - FBSDKCoreKit/Basics (9.0.1)
  - Firebase/Auth (7.7.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 7.7.0)
  - Firebase/Core (7.7.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 7.7.0)
  - Firebase/CoreOnly (7.7.0):
    - FirebaseCore (= 7.7.0)
  - Firebase/Crashlytics (7.7.0):
    - Firebase/CoreOnly
    - FirebaseCrashlytics (~> 7.7.0)
  - Firebase/Firestore (7.7.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (~> 7.7.0)
  - Firebase/RemoteConfig (7.7.0):
    - Firebase/CoreOnly
    - FirebaseRemoteConfig (~> 7.7.0)
  - FirebaseABTesting (7.7.0):
    - FirebaseCore (~> 7.0)
  - FirebaseAnalytics (7.7.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleAppMeasurement (= 7.7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30907.0)
  - FirebaseAuth (7.7.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GTMSessionFetcher/Core (~> 1.4)
  - FirebaseCore (7.7.0):
    - FirebaseCoreDiagnostics (~> 7.4)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
  - FirebaseCoreDiagnostics (7.7.0):
    - GoogleDataTransport (~> 8.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/Logger (~> 7.0)
    - nanopb (~> 2.30907.0)
  - FirebaseCrashlytics (7.7.0):
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleDataTransport (~> 8.0)
    - nanopb (~> 2.30907.0)
    - PromisesObjC (~> 1.2)
  - FirebaseFirestore (7.7.0):
    - abseil/algorithm (= 0.20200225.0)
    - abseil/base (= 0.20200225.0)
    - abseil/memory (= 0.20200225.0)
    - abseil/meta (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/time (= 0.20200225.0)
    - abseil/types (= 0.20200225.0)
    - FirebaseCore (~> 7.0)
    - "gRPC-C++ (~> 1.28.0)"
    - leveldb-library (~> 1.22)
    - nanopb (~> 2.30907.0)
  - FirebaseInstallations (7.7.0):
    - FirebaseCore (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - GoogleUtilities/UserDefaults (~> 7.0)
    - PromisesObjC (~> 1.2)
  - FirebaseRemoteConfig (7.7.0):
    - FirebaseABTesting (~> 7.0)
    - FirebaseCore (~> 7.0)
    - FirebaseInstallations (~> 7.0)
    - GoogleUtilities/Environment (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
  - Google-Mobile-Ads-SDK (8.1.0):
    - GoogleAppMeasurement (~> 7.0)
    - GoogleUserMessagingPlatform (~> 1.1)
  - GoogleAppMeasurement (7.7.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 7.0)
    - GoogleUtilities/MethodSwizzler (~> 7.0)
    - GoogleUtilities/Network (~> 7.0)
    - "GoogleUtilities/NSData+zlib (~> 7.0)"
    - nanopb (~> 2.30907.0)
  - GoogleDataTransport (8.2.0):
    - nanopb (~> 2.30907.0)
  - GoogleUserMessagingPlatform (1.4.0)
  - GoogleUtilities/AppDelegateSwizzler (7.2.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.2.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (7.2.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (7.2.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (7.2.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.2.2)"
  - GoogleUtilities/Reachability (7.2.2):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (7.2.2):
    - GoogleUtilities/Logger
  - "gRPC-C++ (1.28.2)":
    - "gRPC-C++/Implementation (= 1.28.2)"
    - "gRPC-C++/Interface (= 1.28.2)"
  - "gRPC-C++/Implementation (1.28.2)":
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - "gRPC-C++/Interface (= 1.28.2)"
    - gRPC-Core (= 1.28.2)
  - "gRPC-C++/Interface (1.28.2)"
  - gRPC-Core (1.28.2):
    - gRPC-Core/Implementation (= 1.28.2)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Implementation (1.28.2):
    - abseil/container/inlined_vector (= 0.20200225.0)
    - abseil/memory/memory (= 0.20200225.0)
    - abseil/strings/str_format (= 0.20200225.0)
    - abseil/strings/strings (= 0.20200225.0)
    - abseil/types/optional (= 0.20200225.0)
    - BoringSSL-GRPC (= 0.0.7)
    - gRPC-Core/Interface (= 1.28.2)
  - gRPC-Core/Interface (1.28.2)
  - GTMSessionFetcher/Core (1.5.0)
  - InMobiSDK (9.1.5):
    - InMobiSDK/InMobiSDK (= 9.1.5)
  - InMobiSDK/Core (9.1.5)
  - InMobiSDK/InMobiSDK (9.1.5):
    - InMobiSDK/Core
    - InMobiSDK/Moat
  - InMobiSDK/Moat (9.1.5):
    - InMobiSDK/Core
  - IronSourceSDK (7.1.1.0)
  - leveldb-library (1.22)
  - nanopb (2.30907.0):
    - nanopb/decode (= 2.30907.0)
    - nanopb/encode (= 2.30907.0)
  - nanopb/decode (2.30907.0)
  - nanopb/encode (2.30907.0)
  - PromisesObjC (1.2.12)
  - RMStore (0.7.1):
    - RMStore/Core (= 0.7.1)
  - RMStore/Core (0.7.1)
  - RMStore/KeychainPersistence (0.7.1):
    - RMStore/Core
  - Siesta (1.5.2):
    - Siesta/Core (= 1.5.2)
  - Siesta/Core (1.5.2)
  - StreamingKit (0.1.30)
  - "UIViewController+BackButtonHandler (1.0.0)"
  - UnityAds (3.6.0)

DEPENDENCIES:
  - AdColony
  - Appirater
  - AppLovinSDK
  - Atributika
  - CocoaLumberjack
  - DZNEmptyDataSet (from `https://github.com/skajake/DZNEmptyDataSet.git`)
  - EDSunriseSet
  - FairBidSDK
  - FBAudienceNetwork
  - Firebase/Auth
  - Firebase/Core
  - Firebase/Crashlytics
  - Firebase/Firestore
  - Firebase/RemoteConfig
  - Google-Mobile-Ads-SDK
  - InMobiSDK
  - IronSourceSDK
  - RMStore (from `https://github.com/robotmedia/RMStore.git`)
  - RMStore/KeychainPersistence (from `https://github.com/robotmedia/RMStore.git`)
  - Siesta (~> 1.0)
  - StreamingKit
  - "UIViewController+BackButtonHandler (from `https://github.com/onegray/UIViewController-BackButtonHandler.git`)"
  - UnityAds

SPEC REPOS:
  trunk:
    - abseil
    - AdColony
    - Appirater
    - AppLovinSDK
    - Atributika
    - BoringSSL-GRPC
    - CocoaLumberjack
    - EDSunriseSet
    - FairBidSDK
    - FBAudienceNetwork
    - FBSDKCoreKit
    - Firebase
    - FirebaseABTesting
    - FirebaseAnalytics
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseCrashlytics
    - FirebaseFirestore
    - FirebaseInstallations
    - FirebaseRemoteConfig
    - Google-Mobile-Ads-SDK
    - GoogleAppMeasurement
    - GoogleDataTransport
    - GoogleUserMessagingPlatform
    - GoogleUtilities
    - "gRPC-C++"
    - gRPC-Core
    - GTMSessionFetcher
    - InMobiSDK
    - IronSourceSDK
    - leveldb-library
    - nanopb
    - PromisesObjC
    - Siesta
    - StreamingKit
    - UnityAds

EXTERNAL SOURCES:
  DZNEmptyDataSet:
    :git: https://github.com/skajake/DZNEmptyDataSet.git
  RMStore:
    :git: https://github.com/robotmedia/RMStore.git
  "UIViewController+BackButtonHandler":
    :git: https://github.com/onegray/UIViewController-BackButtonHandler.git

CHECKOUT OPTIONS:
  DZNEmptyDataSet:
    :commit: 3bd9a5db07d8f9422acfbf7b0dc4c29fec1eaa5e
    :git: https://github.com/skajake/DZNEmptyDataSet.git
  RMStore:
    :commit: 303b1e9625a80b21e195e7a58034f33a63edbeb1
    :git: https://github.com/robotmedia/RMStore.git
  "UIViewController+BackButtonHandler":
    :commit: 74437b25aa306e7d8f45f2734c760d7c56935663
    :git: https://github.com/onegray/UIViewController-BackButtonHandler.git

SPEC CHECKSUMS:
  abseil: 6c8eb7892aefa08d929b39f9bb108e5367e3228f
  AdColony: e54ee1d060491410135a5a1c9b010bcb4a171dab
  Appirater: 44a4651f7912a17dc906b655f0c215d5bb768b84
  AppLovinSDK: fc91aca5b6b529cae7181a43f63633363dddbe3b
  Atributika: cf87f95f1d31d9cdb9af611a2b4e00672e9ae195
  BoringSSL-GRPC: 8edf627ee524575e2f8d19d56f068b448eea3879
  CocoaLumberjack: e8955b9d337ac307103b0a34fd141c32f27e53c5
  DZNEmptyDataSet: b94434220f87d9dda46660eb4f07a424778e93b4
  EDSunriseSet: bdc4760f496c8e6f9b9a727ffa645b6048aa2a09
  FairBidSDK: ed1b01712b537fb4d4ba6ea10889db6b5cc7e9b3
  FBAudienceNetwork: 58b4d0f2359783e5bc9ee59f138b4fda43173ac4
  FBSDKCoreKit: fada1a6a0076724678993ff05a633848765ff18c
  Firebase: cd2ab85eec8170dc260186159f21072ecb679ad5
  FirebaseABTesting: 96117eb86e2fa429520bbf5a3f02caef615f6576
  FirebaseAnalytics: f3f8f75de34fe04141a69bb1c4bd7e24a80178e1
  FirebaseAuth: 76aa97ecd51e20ecd21321d08474d25f5d2b7b9f
  FirebaseCore: ac35d680a0bf32319a59966a1478e0741536b97b
  FirebaseCoreDiagnostics: 179bf3831213451c8addd036aca7fcf5492ec154
  FirebaseCrashlytics: 47af228115805e190b566db12c028263531b8ce0
  FirebaseFirestore: 5e314d8ad3280576d641caf228f399dfb74f7914
  FirebaseInstallations: 42c86e7b02ff75b7f27f85833bf5dcb5f38a9774
  FirebaseRemoteConfig: 44024544404d1195537bd883b60d596d95e129b7
  Google-Mobile-Ads-SDK: efb7fb74595668fbbe680f0d1c06f9a8ff694c7c
  GoogleAppMeasurement: 0c3b134b2c0a90c4c24833873894bfe0e42a0384
  GoogleDataTransport: 1024b1a4dfbd7a0e92cb20d7e0a6f1fb66b449a4
  GoogleUserMessagingPlatform: b168e8c46cd8f92aa3e34b584c4ca78a411ce367
  GoogleUtilities: 31c5b01f978a70c6cff2afc6272b3f1921614b43
  "gRPC-C++": 13d8ccef97d5c3c441b7e3c529ef28ebee86fad2
  gRPC-Core: 4afa11bfbedf7cdecd04de535a9e046893404ed5
  GTMSessionFetcher: b3503b20a988c4e20cc189aa798fd18220133f52
  InMobiSDK: 4f30f1c2dc10e15ce897166b063c5f0c85829cff
  IronSourceSDK: 6eb315501b51ba7651522c893a1bae260cfef988
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  nanopb: 59221d7f958fb711001e6a449489542d92ae113e
  PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97
  RMStore: 532969d77cc7f1fb4033d0b08b4ca5625d91ee49
  Siesta: d1e1966af43ffca170f658ad6d987228a5b40873
  StreamingKit: 70ca8608c206864b4d54a577eacb3c8bf7c72209
  "UIViewController+BackButtonHandler": fd4b629a0ce8d2d5af180ce6af14a19eea363e1c
  UnityAds: 3f88cf3d3b11991de1025fcf0e3109fd86035fba

PODFILE CHECKSUM: d0712631293cece9a4a1cc5db31c07f24c2a55b1

COCOAPODS: 1.10.1
```

**Comment by paulb777** [comment]
Hmm. I don't see an explanation from this data. I would suggest running `pod deintegrate`, opening the xcodeproj, and doing a thorough review of the Build Settings, especially the Linker options.

Beyond that, we'll likely need a fully reproducible example to provide more assistance.

**Comment by skajake** [comment]
Thanks Paul.  I will see if I can make a small reproducible sample from my project file.

**Comment by skajake** [comment]
Paul, here is my sample workspace.  

https://www.dropbox.com/s/d8d4ie48syydyda/Example.zip?dl=0

**Comment by paulb777** [comment]
Thanks for sharing the repro.

The problem is that project's `Framework Search Paths` Build Setting doesn't work now that some of the frameworks are now part of xcframeworks.  It successfully builds after clearing:

![Screen Shot 2021-02-26 at 10 42 27 AM](https://user-images.githubusercontent.com/73870/109341805-c3d88b80-781f-11eb-906e-09e19dc7f73b.png)

**Comment by skajake** [comment]
Thank you, outstanding support!
