### ISSUE TITLE
Swift 5.9 Support

### ISSUE THREAD

**Issue by mostafa-v** [firebase/firebase-ios-sdk#11947]
### Description

I have the following error when building my project.

Failed to build module 'FirebaseCoreInternal'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.

What should I do? Do I need to change anything in my build settings, or Should I build framework myself with swift 5.9 or should I wait for next release?

Please help

### Firebase SDK Version

10.16.0

### Xcode Version

15.0

### Installation Method

N/A

### Firebase Product(s)

Analytics

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
What is the Installation Method?

**Comment by mostafa-v** [comment]
Hi

I use Bazelbuild to build my project. I added Firebase by swift package, and also by xcframeworks. both of the methods fails.

Just to give you more info, the failure is just for FirebaseCoreInternal library. I can use Firebase 8.x in my project.

Also I used Firebase 9.x and 10.x in my project when the project was on XCode 14.2, 14.3. But since the project is now on Xcode 15, this error happens.

**Comment by paulb777** [comment]
Hmm, I could potentially see the issue with the xcframework, but really strange to see it via the SPM source build that should build FirebaseCoreInternal with the same Swift as the app.

**Comment by mostafa-v** [comment]
Hi
I don't have the exact reason of failure when I use SPM, but it is also about building FirebaseCoreInternal.

The error I sent was for when I use xcframeworks. I always used the xcframework method in my project and I just tried SPM when it failed.

Could I have xcframeworks built for swift 5.9 anyway? 

or else I should dig into the SPM method to catch more info.

**Comment by paulb777** [comment]
xcframeworks (and Xcode built binaries in general) should be forward compatible, so we'll need to investigate more deeply to understand why that's not working

**Comment by mostafa-v** [comment]
Is there any update?

**Comment by paulb777** [comment]
We may need a reproduction example in Xcode or xcodebuild.

**Comment by mostafa-v** [comment]
My project is a complex one which is built with a special tool called BazelBuild. And I think if I provide a simple example Xcode project, the issue wouldn't rise.

I downloaded the new version (10.17), but it seems that it is still not built with swift 5.9. 

The things is I think I just need a xcframework for FirebaseCoreInternal built with swift 5.9 (Xcode 15). How can I have that?

**Comment by mostafa-v** [comment]
> One way would be to update the Xcode version in the package-release build script at https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/zip.yml

I tried this method and changed the workflow to build with xcode 15 and macos 13. but the workflow failed.

[my workflow](https://github.com/mostafa-v/firebase-ios-sdk/actions/runs/6840285579)

`error: cannot compute path of binary 'Path(str: "/private/var/folders/q4/3s60g5510ydbd3qc3p4xflm80000gn/T/ZipRelease/2023-11-12T11-06-44/platform_frameworks/catalyst/FBLPromises.framework/FBLPromises")' relative to that of '/var/folders/q4/3s60g5510ydbd3qc3p4xflm80000gn/T/ZipRelease/2023-11-12T11-06-44/platform_frameworks/catalyst/FBLPromises.framework'
ZipBuilder/FrameworkBuilder.swift:722: Fatal error: Could not build xcframework for PromisesObjC exit code 70: 
scripts/build_zip.sh: line 51: 12632 Illegal instruction: 4  swift run zip-builder --keep-build-artifacts --update-pod-repo ${build_head_option} ${build_head_value} --output-dir "${OUTPUT_DIR}" "${carthage_version_check}" --custom-spec-repos "${specrepo[@]}"`

As I investigated, I found that this error raises in xcode 15 because a [bug](https://developer.apple.com/forums/thread/738070) about symlinks. But I couldn't fix it. Could you please help?

**Comment by ryang1428** [comment]
Running into the same thing trying to update to 10.18.0 using xcframeworks on Xcode 15.0.1. The only one giving me issues is RemoteConfig

```Failed to build module 'FirebaseRemoteConfig'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.```

The odd thing is our swift version is set to 5.7.1 in our Package files 🤷‍♂️

**Comment by paulb777** [comment]
@ryang1428 We've confirmed using the zip distro's xcframeworks to build with 15.0.1 at https://github.com/firebase/firebase-ios-sdk/actions/runs/6884604731/job/18731113775?pr=12101.  

We'll likely need an Xcode project using one of the Firebase xcframeworks that reproduces the issue to make progress on this issue.

**Comment by vixez** [comment]
Having this exact issue.
I cannot upgrade the Flutter packages to the latest version (`10.18.0`), as it breaks the iOS builds with the `SDK is not supported by the compiler` error.

**Comment by mostafa-v** [comment]
> @ryang1428 We've confirmed using the zip distro's xcframeworks to build with 15.0.1 at https://github.com/firebase/firebase-ios-sdk/actions/runs/6884604731/job/18731113775?pr=12101.
> 
> We'll likely need an Xcode project using one of the Firebase xcframeworks that reproduces the issue to make progress on this issue.

How can I get the xcframeworks you built with xcode 15.0.1?

**Comment by paulb777** [comment]
To clarify, we didn't build the xcframeworks with xcode 15.0.1, we ran tests with Xcode 14.1-built xcframeworks linked into apps built with Xcode 15.0.1

**Comment by mostafa-v** [comment]
But I still can't link Xcode 14.1 built xcframeworks in my project. Also I can't build xcframeworks with xcode 15 because of strange "cannot compute path of binary" error I mentioned earlier.

**Comment by ncooke3** [comment]
> We have run into the same issue with [our project.](https://github.com/adobe/aepsdk-core-ios). Very easy to reproduce by creating an XCFramework with Xcode 14 tooling and then attempting to use the XCFramework on Xcode 15. We have logged a radar with Apple (FB13315364).

Hi @cdhoffmann, did you get a resolution with regard to FB13315364?

**Comment by mostafa-v** [comment]
> Hi @mostafa-v, just so I understand, you are able to reproduce the issue by including the `FirebaseCoreInternal.xcframework` in your project, correct? I'm trying to understand if you are building FirebaseCoreInternal from source or using the pre-compiled xcframework from the Firebase zip. Or, does the issue surface in both cases?

Hi
First of all, my project is using a special build system, BazelBuild.

I tried many ways. The issue is happening when I add FirebaseCoreInternal. I always have used xcframeworks from Firebase zip  in my project and everything worked great until when I must update my project to XCode 15., but I got errors with FirebaseCoreInternal xcframework. 

I tried to use swift package manager this time, but I had no success, although I'm not sure if I did everything right or not in the Bazel buildsystem (I have never used swift package manager in my project) .

Also I tried to build the xcframeworks with Xcode 15 myself and I did so by forking the repo and changing github actions to build the zip with Xcode 15, but I got a strange error which I think it is related to some bugs in Xcode 15.

I don't know what to do now. Wait for apple to fix its bugs, wait for firebase team to build zip with Xcode 15 or maybe it will get fixed in future updates of Bazel building system which my project use.

**Comment by mostafa-v** [comment]
The errors are still happening on XCode 15.1 and I haven't found any solution yet.

**Comment by mostafa-v** [comment]
Finally I've successfully added Firebase to my XCode 15 project using Swift Package Manager.

**Comment by paulb777** [comment]
Great news! Are you able to share the solution for anyone else running into this?

**Comment by mostafa-v** [comment]
I still couldn't solve the issue with the zip xcframeworks.

I just figured how to correctly integrate Firebase with SPM method in my bazelbuild project, so there is no need to use the zip method anymore.

**Comment by mostafa-v** [comment]
Is there any plan to publish xcframeworks built with Xcode 15 (swift 5.9)?

**Comment by ncooke3** [comment]
Hi @mostafa-v, yes, but I do not have an ETA at this time. It will likely be after Apple starts requiring Xcode 15 for App Store submissions (likely sometime this Spring).
