### ISSUE TITLE
FirebaseAuth module not found from ObjC bridging header on visionOS

### ISSUE THREAD

**Issue by triplef** [firebase/firebase-ios-sdk#14837]
### Description

Importing FirebaseAuth from an Objective-C header that is included in a bridging header causes `error: module 'FirebaseAuth' not found`.

This is a regression in Firebase SDK v11 and works correctly with the latest v10.29.0. It seems to only affect FirebaseAuth, as importing other modules like FirebaseCore still works correctly.

### Reproducing the issue

Example project: [FBVisionTest.zip](https://github.com/user-attachments/files/20122712/FBVisionTest.zip)

Created like this:
1. Create a visionOS app project in Xcode
2. Add Firebase dependency, linking against FirebaseCore and FirebaseAuth
3. Add an Objective-C class and a bridging header
4. Import the ObjC header in the bridging header
5. Add `@import FirebaseAuth;` to the ObjC header

### Firebase SDK Version

11.12.0

### Xcode Version

16.3

### Installation Method

Swift Package Manager

### Firebase Product(s)

Authentication

### Targeted Platforms

visionOS

### Relevant Log Output

```shell
PrecompileSwiftBridgingHeader normal arm64 (in target 'FBVisionTest' from project 'FBVisionTest')
    cd /tmp/FBVisionTest
    

/tmp/FBVisionTest/FBVisionTest/FBVisionTest-Bridging-Header.h:6:9: note: in file included from /tmp/FBVisionTest/FBVisionTest/FBVisionTest-Bridging-Header.h:6:
#import "ObjCTest.h"
        ^
/tmp/FBVisionTest/FBVisionTest/ObjCTest.h:9:9: error: module 'FirebaseAuth' not found
@import FirebaseAuth;
        ^
<unknown>:0: error: failed to emit precompiled header '/Users/me/Library/Developer/Xcode/DerivedData/FBVisionTest-fdckjfnmwisrreeqygakkgbqixfu/Build/Intermediates.noindex/PrecompiledHeaders/FBVisionTest-Bridging-Header-swift_1FRJAGOOB9OXP-clang_1L1P3A83JHBYD.pch' for bridging header '/tmp/FBVisionTest/FBVisionTest/FBVisionTest-Bridging-Header.h'
/tmp/FBVisionTest/FBVisionTest/FBVisionTest-Bridging-Header.h:6:9: note: in file included from /tmp/FBVisionTest/FBVisionTest/FBVisionTest-Bridging-Header.h:6:
#import "ObjCTest.h"
        ^
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json
{
  "originHash" : "3cf219dd9c99475c717ac7ae1725d003ae3c9d6d70368eba8d3b2a850b07ca97",
  "pins" : [
    {
      "identity" : "abseil-cpp-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/abseil-cpp-binary.git",
      "state" : {
        "revision" : "bbe8b69694d7873315fd3a4ad41efe043e1c07c5",
        "version" : "1.2024072200.0"
      }
    },
    {
      "identity" : "app-check",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/app-check.git",
      "state" : {
        "revision" : "61b85103a1aeed8218f17c794687781505fbbef5",
        "version" : "11.2.0"
      }
    },
    {
      "identity" : "firebase-ios-sdk",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/firebase-ios-sdk.git",
      "state" : {
        "revision" : "fbd463894af94d90eb4d6a4e54080459a8179519",
        "version" : "11.12.0"
      }
    },
    {
      "identity" : "googleappmeasurement",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleAppMeasurement.git",
      "state" : {
        "revision" : "f7460ea630bddf172115c28493ae8b3798d95ce3",
        "version" : "11.12.0"
      }
    },
    {
      "identity" : "googledatatransport",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleDataTransport.git",
      "state" : {
        "revision" : "617af071af9aa1d6a091d59a202910ac482128f9",
        "version" : "10.1.0"
      }
    },
    {
      "identity" : "googleutilities",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/GoogleUtilities.git",
      "state" : {
        "revision" : "60da361632d0de02786f709bdc0c4df340f7613e",
        "version" : "8.1.0"
      }
    },
    {
      "identity" : "grpc-binary",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/grpc-binary.git",
      "state" : {
        "revision" : "cc0001a0cf963aa40501d9c2b181e7fc9fd8ec71",
        "version" : "1.69.0"
      }
    },
    {
      "identity" : "gtm-session-fetcher",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/gtm-session-fetcher.git",
      "state" : {
        "revision" : "c756a29784521063b6a1202907e2cc47f41b667c",
        "version" : "4.5.0"
      }
    },
    {
      "identity" : "interop-ios-for-google-sdks",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/interop-ios-for-google-sdks.git",
      "state" : {
        "revision" : "040d087ac2267d2ddd4cca36c757d1c6a05fdbfe",
        "version" : "101.0.0"
      }
    },
    {
      "identity" : "leveldb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/leveldb.git",
      "state" : {
        "revision" : "a0bc79961d7be727d258d33d5a6b2f1023270ba1",
        "version" : "1.22.5"
      }
    },
    {
      "identity" : "nanopb",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/firebase/nanopb.git",
      "state" : {
        "revision" : "b7e1104502eca3a213b46303391ca4d3bc8ddec1",
        "version" : "2.30910.0"
      }
    },
    {
      "identity" : "promises",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/google/promises.git",
      "state" : {
        "revision" : "540318ecedd63d883069ae7f1ed811a2df00b6ac",
        "version" : "2.4.0"
      }
    },
    {
      "identity" : "swift-protobuf",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/apple/swift-protobuf.git",
      "state" : {
        "revision" : "d72aed98f8253ec1aa9ea1141e28150f408cf17f",
        "version" : "1.29.0"
      }
    }
  ],
  "version" : 3
}


```

</details>

**Comment by rizafran** [comment]
Thanks for reporting, @triplef. I was able to reproduce the issue. I'll raise it to our engineers and see what we can do here.

**Comment by ncooke3** [comment]
Sorry for the trouble, @triplef. FirebaseAuth was rewritten in Swift in v11. When compiling the bridging header, SPM does not seem to pass the module map for Swift modules like FirebaseAuth.

Assuming that in your real project, the counterpart to `ObjCTest.h` uses symbols from `FirebaseAuth` in its header,
the best path forward is to move the `FirebaseAuth` import from `ObjCTest.h` into `ObjCTest.m` (the import works in implementation files). Then, in your `ObjCTest.h`, forward declare whatever `FirebaseAuth` types that were used (e.g. `@class FIRAuth;`).

**Comment by KabukiAdam** [comment]
@ncooke3  I also have experienced this issue, but your suggestion of forward-declaring doesn't completely fix this issue. It fixes the `module 'FirebaseAuth' not found` error, but now in any swift code that tries to access the objective-C class, I get an error `Value of type 'MyObjCClass' has no member 'SomeAuthType'`.

For example:
```
//  UserManager.h

@import Foundation;

@class FIRUser;

@interface UserManager : NSObject

@property (strong, nonatomic) FIRUser *currentUser;
@property (strong, nonatomic) NSString *currentString;
@end
```

`UserManager` itself now compiles fine, **but** any Swift code that tries to access `UserManager().currentUser` gets an compile error:
`Value of type 'UserManager' has no member 'currentUser'`

(UserManager.h is included in the bridging header)

Any other suggestions?

**Comment by KabukiAdam** [comment]
> [@KabukiAdam](https://github.com/KabukiAdam), does the Swift code also import FirebaseAuth?

@ncooke3 Yes, it does. I have a very simple sample project for this issue if that helps.

**Comment by KabukiAdam** [comment]
@ncooke3 Thanks!

I have a repo with a small Xcode project here:
https://github.com/KabukiAdam/Swifttest

The Objective-C class UserManager contains a property of type FIRUser:
```
@import Foundation;

@class FIRUser;

@interface UserManager : NSObject

@property (strong, nonatomic) FIRUser *currentUser;
@property (strong, nonatomic) NSString *currentString;
@end
```

The swift code in ContentView tries to access the `currentUser` property and gets an error.
```
// ERROR: Value of type 'UserManager' has no member 'currentUser'
let user = UserManager().currentUser
```

I appreciate your time on this!

**Comment by ncooke3** [comment]
No problem, and thanks for the repro. I have a workaround worth testing: adding `$(OBJROOT)/GeneratedModuleMaps` to your target's header search paths build setting.

<img width="588" alt="Image" src="https://github.com/user-attachments/assets/f2a0c35b-dce9-4a14-82d5-753497e23aef" />

With this workaround, you can replace the forward declaration with `#import "FirebaseAuth-Swift.h"`.

--- 

Based on the builds logs, Xcode is not passing the generated "FirebaseAuth-Swift.h" Swift header to the ObjC half of your target. 

The final version of the generated header is stored within `$(OBJROOT)/GeneratedModuleMaps` with other module artifacts.

<img width="1033" alt="Image" src="https://github.com/user-attachments/assets/51b3f11d-bbbe-4437-872e-1775caa5be96" />

I believe this is a unique case where, within a single target, Swift code (ContentView) is depending on ObjC code (UserManager) that depends on Swift code (FirebaseAuth), but this solution seems promising. I'd recommend testing that the archived version of the app functions correctly with it.

**Comment by KabukiAdam** [comment]
Thanks @ncooke3, that does seem to get me past the compiler error, although I can't yet confirm that everything works since this is part of an overall move to Firebase 11.x SDK and there are some other changes needed in our code base.

I don't love this workaround of having to manually add the header search path since that GeneratedModuleMaps path seems like an internal detail that future build systems could change. It feels a bit too fragile maybe. I'll bring it to our team and see if we want to move forward with it or maybe hold off on moving to Firebase 11.x SDK until we can maybe port some of these ObjC classes to Swift.

Thanks again for the looking at this.

**Comment by ncooke3** [comment]
Ah, apologies for the misdirection, @KabukiAdam. I suppose Xcode doesn't expose the header by default for a reason.

I can think of two other options that avoid build settings hacks or porting code.

1. Define a `FIRUserProtocol` that matches the public interface of `FIRUser` that you need and make that the type of `-[UserManager currentUser ]`.

```objc
@import Foundation;

// TODO: Define `FIRUserProtocol` that matches bits of `FIRUser` you need.

@interface UserManager : NSObject

@property (strong, nonatomic) id<FIRUserProtocol> currentUser; // Change type to id<protocol>
@property (strong, nonatomic) NSString *currentString;
@end
```

Depending on how many Firebase APIs are exposed to the Swift half of your target via your ObC half, this could be lighter weight option.

2. Consider refactoring out the ObjC classes that use Firebase APIs in their public interface (like UserManager) into their own framework target that your app target can imports. There could be a valid path here as it avoids relying on the bridging header for interoperability.
