### ISSUE TITLE
Pod lib lint failed on watchOS PR

### ISSUE THREAD

**Issue by chliangGoogle** [firebase/firebase-ios-sdk#4964]
https://github.com/firebase/firebase-ios-sdk/pull/4955 is blocked by pod lib lint error introduced in #4944. 

Error messages:
    - ERROR | xcodebuild:  /Users/runner/runners/2.165.2/work/firebase-ios-sdk/firebase-ios-sdk/GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTNanopbHelpers.h:124:5: error: unknown type name 'SCNetworkReachabilityFlags'
    - ERROR | [watchOS] xcodebuild:  /Users/runner/runners/2.165.2/work/firebase-ios-sdk/firebase-ios-sdk/GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m:202:3: error: use of undeclared identifier 'SCNetworkReachabilityFlags'

We can also include watchOS in github action of Google Data Transport so we can catch this issue earlier. https://github.com/firebase/firebase-ios-sdk/blob/master/.github/workflows/datatransport.yml

**Comment by doudounan** [comment]
Wrap 'SCNetworkReachabilityFlags' in https://github.com/firebase/firebase-ios-sdk/pull/4965
