### ISSUE TITLE
logEvent causes a crash when an array containing a custom class is sent as a parameter

### ISSUE THREAD

**Issue by l-barbosa** [firebase/firebase-ios-sdk#5967]
### Step 1: Describe your environment

  * Xcode version: 11.5 (11E608c)
  * Firebase SDK version: 6.27.0
  * Firebase Component: Analytics
  * Component version: 6.6.1
  * Installation method: `CocoaPods`

#### Steps to reproduce:

App crashes when trying to log and event where we send as a parameter an Array containing a custom class, even though the method signature says that parameters can be `Any` (https://firebase.google.com/docs/reference/swift/firebaseanalytics/api/reference/Classes/Analytics#logevent_:parameters:)
Example code below along with an example stack trace.

#### Relevant Code:

This is enough to cause the crash:
```
class MyClass {
    
}
...
Analytics.logEvent("Error", parameters: ["param0": ["This is going to crash…", MyClass()]])
```

#### Stacktrace

```
Crashed: APMAnalyticsQueue
0  libsystem_kernel.dylib         0x19050ed88 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1904271e8 pthread_kill$VARIANT$mp + 136
2  libsystem_c.dylib              0x19037a934 abort + 100
3  libswiftCore.dylib             0x19de610a0 swift_vasprintf(char**, char const*, char*) + 54
4  libswiftCore.dylib             0x19dea6868 -[_TtCs12_SwiftObject retain] + 98
5  CoreFoundation                 0x19071d89c ___forwarding___ + 1316
6  CoreFoundation                 0x19071f7cc _CF_forwarding_prep_0 + 92
7  CoreFoundation                 0x1905f3584 -[NSArray initWithArray:range:copyItems:] + 300
8  CoreFoundation                 0x190604384 -[__NSPlaceholderArray initWithArray:copyItems:] + 104
9  AppName                    0x104917e40 -[APMValue initWithArray:] + 4336959040
10 AppName                    0x104917a68 +[APMValue valueFromObject:allowArray:] + 4336958056
11 AppName                    0x104940ab0 APMNormalizedParametersForParametersAndEventName + 4337126064
12 AppName                    0x1049155c8 -[APMEvent initWithOrigin:isPublic:name:timestamp:previousTimestamp:parameters:] + 4336948680
13 AppName                    0x1048db844 +[APMAnalytics eventsToLogWithEventID:origin:isPublic:name:timestamp:parameters:] + 4336711748
14 AppName                    0x1048db420 +[APMAnalytics logEventOnSerialQueueWithOrigin:isPublicEvent:name:parameters:timestamp:ignoreEnabled:ignoreInterceptor:addedScreenParameters:] + 4336710688
15 AppName                    0x1048db0b8 __65+[APMAnalytics logEventWithOrigin:isPublicEvent:name:parameters:]_block_invoke_3 + 4336709816
16 libdispatch.dylib              0x1903de9a8 _dispatch_call_block_and_release + 24
17 libdispatch.dylib              0x1903df524 _dispatch_client_callout + 16
18 libdispatch.dylib              0x19038b8a4 _dispatch_lane_serial_drain$VARIANT$mp + 608
19 libdispatch.dylib              0x19038c294 _dispatch_lane_invoke$VARIANT$mp + 416
20 libdispatch.dylib              0x19039578c _dispatch_workloop_worker_thread + 588
21 libsystem_pthread.dylib        0x190430b74 _pthread_wqthread + 272
22 libsystem_pthread.dylib        0x190433740 start_wqthread + 8
```

#### Console log

We do get a warning before the crash:
```
2020-07-02 22:39:50.329204+0100 FirebaseCrash[25517:773134] 6.27.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=404, type=2, request_id=, content_type=text/html; charset=utf-8}
2020-07-02 22:39:51.163351+0100 FirebaseCrash[25517:773099] *** NSForwarding: warning: object 0x6000038aa710 of class 'FirebaseCrash.MyClass' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[FirebaseCrash.MyClass copyWithZone:]
2020-07-02 22:39:51.163563+0100 FirebaseCrash[25517:773099] Unrecognized selector -[FirebaseCrash.MyClass copyWithZone:]
```

#### Notes

I know the code that causes the crash doesn't make much sense but something like this was actually in an app as a result of an abstraction layer that was logging errors to Firebase and in one instance instead of sending the error (which would end up logging the description of the error), sent an array instead.
This code was in the app for a long time without crashes so I believe the problem appeared after upgrading to 6.6.1. Unfortunately I didn't commit the Podfile.lock file so I can't say from which version I upgraded from.
Just thought I should report this as there is the expectation that the code of a framework like this shouldn't ever cause a crash, no matter how silly the invocation.

**Comment by morganchen12** [comment]
This crash happens because Analytics only accepts ObjC objects. You can fix it by making your Swift class an ObjC class (by prepending `@objc` to the class declaration).

The `Any` parameter type is tricky. Swift automatically bridges `id` in ObjC to `Any`, so you get support for primitive types like `Int` for free. If we were to change the type requirements to `[String: NSObjectProtocol]`, this crash would be caught as a type error at compile time, but then you wouldn't be able to pass in `["value": 100]` without explicitly creating an NSNumber from the integer. We saw a similar issue with Swift-only values in #2465.

Generally this isn't an issue because custom object types aren't usually displayed in ways that are useful in Analytics console. What are you trying to achieve by logging a custom object in the parameters dictionary?

**Comment by l-barbosa** [comment]
The impacted app has a custom logging framework that in the event of a non-fatal but unexpected error would log the event name "error" to Analytics with additional info as parameters. 
In one particular instance, due to forwarding of variadic parameters, instead of receiving the variadic parameters to log (which get looped over to form different key-value pairs), it would pass them as an array of arrays and the looping would simple create one key which would have as the value, an array of the original objects.

Even though this particular situation was an error on our side (that since reporting this has been fixed and deployed), we have several logs of this particular instance that now caused the crash from previous versions without crashing.

To give you a bit more detail, the code that now crashed was (without us realising it) doing something like this:

`logEvent("Error", ["param0": ["Error title", CustomErrorObject()]])`

`CustomErrorObject` is a class implementing protocol `LocalizedError`

After fixing the issue on our side, this is what it was supposed to be doing, and it doesn't crash:

`logEvent("Error", ["param0": "Error title", "param1" : CustomErrorObject()])`

So it seems that it wasn't so much the custom class but more the fact that it was within an array.

Anyway, the error in our code has been fixed and the issue is no longer occurring.
I thought I should report this in case there is anything you can do to catch this at compile time but I understand that if you're working in ObjC with all the bridging this may not be possible for Swift users.
Interesting how it wasn't crashing before upgrading though.

Thanks for looking into this.

**Comment by morganchen12** [comment]
The crash vs non-crash is likely caused by an implementation detail in how Analytics serializes events before sending them to the server, and will probably not be changed unless it starts creating a significant volume of crashes. We could add some diagnostic logging like we did in #2465, but the runtime log is pretty clear in this scenario imo. @eburley I will leave the decision of whether or not to make a code change to you, if not feel free to close this issue.

Thanks for reporting @l-barbosa!

**Comment by morganchen12** [comment]
Closing this bug without code changes.
