### ISSUE TITLE
No known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'

### ISSUE THREAD

**Issue by sryze** [firebase/firebase-ios-sdk#6483]
### Step 0: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ please use the Feature Request template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the `firebase` tag.
  * For general (non-iOS) Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For backend issues, console issues, and other non-SDK help that does not fall under one
    of the above categories, reach out to
    [Firebase Support](https://firebase.google.com/support/).
  * Once you've read this section and determined that your issue is appropriate for
    this repository, please delete this section.

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: Version 9.2 (9C40b)
  * Firebase SDK version: 6.28.1
  * Firebase Component: GoogleDataTransport
  * Component version: 7.1.0
  * Installation method: `CocoaPods`

#### Steps to reproduce:

Compile on Xcode 9.2

Actual compiler output:

```
myapp/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m:204:35: error: no known class method for selector 'archivedDataWithRootObject:requiringSecureCoding:error:'
    resultData = [NSKeyedArchiver archivedDataWithRootObject:obj
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
myapp/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m:260:45: error: no known class method for selector 'unarchivedObjectOfClass:fromData:error:'
      unarchivedObject = [NSKeyedUnarchiver unarchivedObjectOfClass:archiveClass
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

#### Relevant Code:

```obj-c
NSData *_Nullable GDTCOREncodeArchive(id<NSSecureCoding> obj,
                                      NSString *archivePath,
                                      NSError *_Nullable *error) {
  BOOL result = NO;
  if (archivePath.length > 0) {
    result = [[NSFileManager defaultManager]
              createDirectoryAtPath:[archivePath stringByDeletingLastPathComponent]
        withIntermediateDirectories:YES
                         attributes:nil
                              error:error];
    if (result == NO || *error) {
      GDTCORLogDebug(@"Attempt to create directory failed: path:%@ error:%@", archivePath, *error);
      return nil;
    }
  }
  NSData *resultData;
#if (defined(__IPHONE_11_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000) || \
    (defined(__MAC_10_13) && MAC_OS_X_VERSION_MAX_ALLOWED >= 101300) ||      \
    (defined(__TVOS_11_0) && __TV_OS_VERSION_MAX_ALLOWED >= 110000) ||       \
    (defined(__WATCHOS_4_0) && __WATCH_OS_VERSION_MAX_ALLOWED >= 040000) ||  \
    (defined(TARGET_OS_MACCATALYST) && TARGET_OS_MACCATALYST)
  if (@available(macOS 10.13, iOS 11.0, tvOS 11.0, watchOS 4, *)) {
    resultData = [NSKeyedArchiver archivedDataWithRootObject:obj
                                       requiringSecureCoding:YES
                                                       error:error];
```

**Comment by sryze** [comment]
Proposed solution: change this

```
#if (defined(__IPHONE_11_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000) || \
```

to:

```
#if (defined(__IPHONE_11_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= 110300) || \
```

But I'm not sure if it actually would compile with 11.3 SDK. Maybe it should be 12.0.

**Comment by sryze** [comment]
Apple's website says that this method is available since 11.0 though, it's strange

https://developer.apple.com/documentation/foundation/nskeyedarchiver/2962880-archiveddatawithrootobject

**Comment by sryze** [comment]
Also if this compile-time check is not satisfied, you get another error:

```obj-c
myapp/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m:244:3: error: expected identifier or '('
  return resultData;
  ^
myapp/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m:245:1: error: extraneous closing brace ('}')
}
^
myapp/ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCORLibrary/GDTCORPlatform.m:260:45: error: no known class method for selector 'unarchivedObjectOfClass:fromData:error:'
      unarchivedObject = [NSKeyedUnarchiver unarchivedObjectOfClass:archiveClass
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
```

I fixed it by commenting out the extra curly bracket before `return resultData;`

**Comment by ryanwilson** [comment]
Thanks for the report @sryze. 

Are you able to open a PR for this? We can't look at the proposed code unfortunately until a CLA is signed (during the PR process). Either that or we can go about creating our own fix with the errors you pointed out. Thanks!

**Comment by maksymmalyhin** [comment]
Extra pre Xcode 10 compatibility checks removed with required fixes. 
Sorry, we officially support only Xcode 11 and higher and don't have plans to support previous versions.
