### PR TITLE
feat(ai): add support for RealtimeInputConfig

### PR DESCRIPTION
**Pull request by daymxn**
Per [b/538190669](https://b.corp.google.com/issues/538190669),

This adds support for the `RealtimeInputConfig` type (within `LiveGenerationConfig`), as well as the `sendStartActivityRealtime()` and `sendStartActivityRealtime()` methods to `LiveSession`.

Tests have also been added for these new features.

Additionally, the existing tests have been modified slightly to take advantage of a util method that will timeout after waiting some predefined seconds for an audio output transcript, as well as handle the case of the model sending randomly sending intermediate empty responses. This should hopefully help prevent our tests from stalling for excessive amounts of time when the server is having issues. Although, the default timeout duration may need to be adjusted. It can be set on a test-by-test basis, but the default is currently set at 5 seconds; which may or may not be sufficient in a CI environment.

### CODE REVIEW

File: FirebaseAI/Sources/Types/Public/Live/ActivityDetectionConfig.swift [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+
+import Foundation
+
+/// Configures the model's automatic detection of user activity.
+///
+/// **Public Preview**: This API is a public preview and may be subject to change.
+///
+///  - seealso: ``RealtimeInputConfig``
+public struct ActivityDetectionConfig: Sendable {
+  let bidiActivitiyDetectionConfig: BidiActivityDetectionConfig
```
Comment (andrewheard) [inline FirebaseAI/Sources/Types/Public/Live/ActivityDetectionConfig.swift]:
```suggestion
  let bidiActivityDetectionConfig: BidiActivityDetectionConfig
```

File: FirebaseAI/Sources/Types/Public/Live/RealtimeInputConfig.swift [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+  }
+
+  init(_ bidiRealtimeInputConfig: BidiRealtimeInputConfig) {
+    self.bidiRealtimeInputConfig = bidiRealtimeInputConfig
+  }
+
+  /// Creates a new ``RealtimeInputConfig`` value.
+  ///
+  /// - Parameters:
+  ///   - automaticActivityDetection:Configures automatic activity detection on the model.
```
Comment (andrewheard) [inline FirebaseAI/Sources/Types/Public/Live/RealtimeInputConfig.swift]:
```suggestion
  ///   - automaticActivityDetection: Configures automatic activity detection on the model.
```

File: FirebaseAI/Sources/Types/Public/Live/ActivityDetectionConfig.swift [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+
+    /// The model will detect speech more often.
+    ///
+    /// In other words, a lower volume of speech is required for the model
+    /// to consider the user is speaking.
+    case high
+  }
+
+  init(_ bidiActivityDetectionConfig: BidiActivityDetectionConfig) {
+    bidiActivityDetectionConfig = bidiActivityDetectionConfig
```
Comment (andrewheard) [inline FirebaseAI/Sources/Types/Public/Live/ActivityDetectionConfig.swift]:
```suggestion
    self.bidiActivityDetectionConfig = bidiActivityDetectionConfig
```

File: FirebaseAI/Tests/TestApp/Tests/Integration/TestHelpers.swift
Comment (andrewheard) [inline FirebaseAI/Tests/TestApp/Tests/Integration/TestHelpers.swift:1]: Please determine if any of these are worth addressing (in particular 3).

---

## 🔍 Concurrency Analysis of `TestHelpers.swift`

The `withTimeout` helper introduced in PR #16441 uses Swift Structured Concurrency (`withThrowingTaskGroup`). While the general concept is solid, there are **3 key concurrency and type-safety issues** to address to ensure full Swift 6 / Strict Concurrency compliance and robust behavior.

```swift
// Original PR Code
static func withTimeout<T>(seconds: Double,
                           operation: @escaping @Sendable () async throws -> T) async throws -> T? {
  try await withThrowingTaskGroup(of: T?.self) { group in
    group.addTask {
      try await operation()
    }
    group.addTask {
      try await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
      return nil
    }

    guard let firstResult = try await group.next() else {
      group.cancelAll()
      return nil
    }

    group.cancelAll()
    return firstResult
  }
}
```

---

### 1. Missing `T: Sendable` Generic Constraint ⚠️
* **Issue:** `T` is returned from a child task (`group.addTask`) and sent across task boundaries to the parent task group.
* **Impact:** In Swift 5.10+ / Swift 6 under `-strict-concurrency=complete`, passing non-`Sendable` types `T` across task boundaries will cause compilation errors or strict concurrency warnings.
* **Fix:** Constrain `T` to `Sendable`: `withTimeout<T: Sendable>`.

---

### 2. Type Ambiguity with Optional Return Types (`T?`) ⚠️
* **Issue:** The task group is created as `withThrowingTaskGroup(of: T?.self)`.
  * If `operation()` itself returns an `Optional` type (e.g., `T = String?`), returning `nil` from `operation()` produces `Optional.some(nil)`.
  * The timeout task *also* returns `nil` (`Optional.some(nil)`).
  * `group.next()` cannot distinguish whether `operation()` completed and returned `nil` or if `Task.sleep` expired.
* **Fix:** Use a private, tagged `enum TimeoutResult<T: Sendable>: Sendable` (`.completed(T)` vs `.timedOut`) instead of relying on `T?`.

---

### 3. Task Group Completion & Cooperative Cancellation Behavior ℹ️
* **Behavior:** When the timeout task finishes first, `group.cancelAll()` is invoked.
* **Structured Concurrency Rule:** Swift structured concurrency guarantees that `withThrowingTaskGroup` **will not return until all child tasks finish**.
  * If `operation()` is cancellation-aware (checks `Task.isCancelled` or uses cancellation-aware APIs like `Task.sleep` / `URLSession`), cancelling it terminates the task immediately.
  * If `operation()` performs a non-cancellable or blocking synchronous call, `withThrowingTaskGroup` will wait for `operation()` to finish before returning—even though `cancelAll()` was called.
* **Recommendation:** Ensure any async operation passed to `withTimeout` respects Task cancellation.

---

### 4. Integer Overflow Hazard on Negative or Extreme `seconds` Values 💡
* **Issue:** `UInt64(seconds * 1_000_000_000)` will crash with a runtime integer overflow trap if `seconds` is negative or exceeds `UInt64.max / 1e9` (~18.4 billion seconds).
* **Fix:** Add a boundary check for `seconds > 0`.

---

## 🛠 Recommended Refactoring

Here is the fully concurrency-safe, Swift 6 compliant implementation:

```swift
private enum TimeoutResult<T: Sendable>: Sendable {
  case completed(T)
  case timedOut
}

enum TestHelpers {
  /// Runs an async operation with a timeout, returning `nil` if the timeout expires before completion.
  static func withTimeout<T: Sendable>(
    seconds: Double,
    operation: @escaping @Sendable () async throws -> T
  ) async throws -> T? {
    guard seconds > 0 else { return nil }
    let nanoseconds = UInt64(min(seconds, 18_000_000_000) * 1_000_000_000)

    return try await withThrowingTaskGroup(of: TimeoutResult<T>.self) { group in
      group.addTask {
        let result = try await operation()
        return .completed(result)
      }

      group.addTask {
        try await Task.sleep(nanoseconds: nanoseconds)
        return .timedOut
      }

      defer { group.cancelAll() }

      while let result = try await group.next() {
        switch result {
        case let .completed(value):
          return value
        case .timedOut:
          return nil
        }
      }

      return nil
    }
  }
}
```

**Review by andrewheard — APPROVED** [review]
LGTM but please run `style.sh`. The integration tests may pass on re-run.
