### ISSUE TITLE
Fatal error after upgrading to 6.27.0 (header file not found)

### ISSUE THREAD

**Issue by mrchristopher124** [firebase/firebase-ios-sdk#5868]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 11.5
  * Firebase SDK version: 6.26.0 prior to update, now 6.27.0
  * Firebase Component: Analytics, Crashlytics, Core, Performance
  * Component version: See below.
  * Installation method: `CocoaPods

### [REQUIRED] Step 2: Describe the problem

Upgraded to the latest versions via cocoapods and now getting this error consistently across projects:

Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Sources/FIRRemoteConfig.m:19:9: fatal error: 'FirebaseABTesting/FIRExperimentController.h' file not found

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

Applicable Podfile entries:

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'

% pod install
Analyzing dependencies
Downloading dependencies
Installing Firebase 6.27.0 (was 6.26.0)
Installing FirebaseABTesting 3.3.0 (was 3.2.0)
Installing FirebaseAnalytics 6.6.1 (was 6.6.0)
Installing FirebaseCore 6.8.0 (was 6.7.2)
Installing FirebaseCoreDiagnostics 1.4.0 (was 1.3.0)
Installing FirebaseCrashlytics 4.2.0 (was 4.1.1)
Installing FirebaseInstallations 1.4.0 (was 1.3.0)
Installing FirebaseRemoteConfig 4.6.0 (was 4.5.0)
Installing GoogleAppMeasurement 6.6.1 (was 6.6.0)
Installing GoogleDataTransportCCTSupport 3.2.0 (was 3.1.0)
Installing RxCoreLocation 1.5.0 (was 1.4.2)
Removing FirebaseAnalyticsInterop
Removing FirebaseCoreDiagnosticsInterop
Generating Pods project
Integrating client project
Pod installation complete! There are 45 dependencies from the Podfile and 64 total pods installed.

[!] Unable to read the license file `LICENSE` for the spec `FirebaseABTesting (3.3.0)`

[!] Unable to read the license file `LICENSE` for the spec `FirebaseABTesting (3.3.0)`

**Comment by mrchristopher124** [comment]
Noting another piece of output from the build:

Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'FirebaseRemoteConfig' from project 'Pods')

**Comment by paulb777** [comment]
@mrchristopher124 Thanks for the report. I'm not able to reproduce on a sample. I suspect something about the build environment or installation has been corrupted. Some things to try - `rm -rf ~/Library/Developer/Xcode/DerivedData/` and `pod cache clean FirebaseABTesting --all`. If that doesn't help, see if you can reproduce on https://github.com/firebase/quickstart-ios/tree/master/config and let us know the CocoaPods version - `pod --version`

**Comment by mrchristopher124** [comment]
@paulb777 ok let me try those thanks Paul! I update pods regularly and haven't had issues with other recent Firebase updates but will report back asap.

**Comment by mrchristopher124** [comment]
@paulb777 I ran those commands and did pod install and a clean build. I now get a different error:

Pods/FirebaseRemoteConfig/FirebaseRemoteConfig/Sources/RCNConfigExperiment.m:19:9: fatal error: 'FirebaseABTesting/ExperimentPayload.pbobjc.h' file not found
#import <FirebaseABTesting/ExperimentPayload.pbobjc.h>

Note that I've never had issues upgrading firebase in the past across multiple apps. I've also tried deleting my Pods directory entirely and reinstalling pods. Doing a complete cache clean of pods. All to no avail unfortunately.

**Comment by paulb777** [comment]
@mrchristopher124 Hmm, there seems to be something strange in your environment and/or HEADER_SEARCH_PATH for the FirebaseABTesting pod.  Are you able to reproduce the issue with a quickstart at https://github.com/firebase/quickstart-ios/tree/master/performance?  What version of CocoaPods?  `pod --version`

**Comment by mrchristopher124** [comment]
@paulb777 Thanks for the response. I am using version 1.9.3 of cocoapods. I can try with the quickstart. Let me give that a go and report back.

**Comment by mrchristopher124** [comment]
@paulb777 I was able to install the pods for that quickstart project and build and run it. Strange. 

For our project's Podfile we have these firebase pods listed:

  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'

Any additional thoughts?

**Comment by paulb777** [comment]
Try searching the source of the .xcodeproj for `FirebaseABTesting`.  There may be something strange about it messing up the configuration.

**Comment by mrchristopher124** [comment]
@paulb777 I ended up doing a clean checkout of the repository and a fresh pod install and now everything is good. No idea! Thanks again for the help!
