### ISSUE TITLE
Duplicate symbol errors with Firebase iOS SDK v5.5.0+

### ISSUE THREAD

**Issue by andwun** [firebase/firebase-ios-sdk#1832]
After upgrading Firebase iOS SDK from v5.4.1 to v5.5.0 or later, duplicate symbol errors make my builds fail:

```
duplicate symbol _pb_field_iter_next in:
    /Users/redacted/Library/Developer/Xcode/DerivedData/redacted-fajkgspepnsyukaipdzoafipxkmd/Build/Products/Debug-iphonesimulator/nanopb/libnanopb.a(pb_common.o)
    /Users/redacted/Documents/Code/redacted/iOS/Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement(pb_common_072e976572d290cdb35c7ac508302b94.o)
[...]
ld: 30 duplicate symbols for architecture x86_64
```

I'm using Cocoapods to integrate Firebase. `use_frameworks!` is not used.

From analyzing `Podfile.lock`, the dependency tree looks like:

* Firebase/Core
  * FirebaseAnalytics
    * nanopb
    * GoogleAppMeasurement
      * nanopb

... so this seems much like a Firebase-internal problem.

Does this mean `use_frameworks!` is now required to use the SDK?
If so, it would be helpful to have this mentioned in the docs and release notes.

### Environment
  * Xcode version: 9.4.1 and 10.0 GM
  * Firebase SDK version: Good: 5.4.1, Bad: 5.5.0
  * Cocoapods version: 1.5.3

**Comment by paulb777** [comment]
CocoaPods should ensure there is only one version of pb_common.o. I suspect the problem is from cruft in DerivedData between Firebase version updates. Does `rm -rf ~/Library/Developer/Xcode/DerivedData` help?  If you're still stuck, please share the `Podfile` and `Podfile.lock`.

**Comment by Piramanayagamm** [comment]
I am also facing the same problem. Removing DerivedData is not helping out. Here is my Pod file

target 'XXX' do
    pod 'UIColor+Hex'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'AFNetworkActivityLogger', '~> 2.0'
    pod 'Lockbox', '~> 2.1.0'
    pod 'libextobjc', '~> 0.4'
    pod 'Mantle', '1.5.4'
    pod 'ReactiveCocoa', '~> 2.0'
    pod 'RSSwizzle', '~> 0.1.0'
    pod 'GoogleTagManager', '3.15.0'
    pod 'UrbanAirship-iOS-SDK', '8.6.0'
    pod 'TOCropViewController', '2.2'
    pod 'UICountingLabel', '~> 1.4.0'
    pod 'Fabric', '1.7.2'
    pod 'Crashlytics', '3.9.3'
    pod 'OptimizelySDKiOS','2.1.0'
    pod 'Firebase/Core'
end

**Comment by Piramanayagamm** [comment]
Podfile.lock

PODS:
  - AFNetworkActivityLogger (2.0.4):
    - AFNetworking/NSURLConnection (~> 2.0)
    - AFNetworking/NSURLSession (~> 2.0)
  - AFNetworking (2.6.3):
    - AFNetworking/NSURLConnection (= 2.6.3)
    - AFNetworking/NSURLSession (= 2.6.3)
    - AFNetworking/Reachability (= 2.6.3)
    - AFNetworking/Security (= 2.6.3)
    - AFNetworking/Serialization (= 2.6.3)
    - AFNetworking/UIKit (= 2.6.3)
  - AFNetworking/NSURLConnection (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/NSURLSession (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (2.6.3)
  - AFNetworking/Security (2.6.3)
  - AFNetworking/Serialization (2.6.3)
  - AFNetworking/UIKit (2.6.3):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
  - Crashlytics (3.9.3):
    - Fabric (~> 1.7.2)
  - Fabric (1.7.2)
  - GoogleAnalytics (3.14.0)
  - GoogleTagManager (3.15.0):
    - GoogleAnalytics (= 3.14.0)
  - libextobjc (0.4.1):
    - libextobjc/EXTADT (= 0.4.1)
    - libextobjc/EXTConcreteProtocol (= 0.4.1)
    - libextobjc/EXTKeyPathCoding (= 0.4.1)
    - libextobjc/EXTNil (= 0.4.1)
    - libextobjc/EXTSafeCategory (= 0.4.1)
    - libextobjc/EXTScope (= 0.4.1)
    - libextobjc/EXTSelectorChecking (= 0.4.1)
    - libextobjc/EXTSynthesize (= 0.4.1)
    - libextobjc/NSInvocation+EXT (= 0.4.1)
    - libextobjc/NSMethodSignature+EXT (= 0.4.1)
    - libextobjc/RuntimeExtensions (= 0.4.1)
    - libextobjc/UmbrellaHeader (= 0.4.1)
  - libextobjc/EXTADT (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTConcreteProtocol (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTKeyPathCoding (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTNil (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTSafeCategory (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTScope (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTSelectorChecking (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/EXTSynthesize (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/NSInvocation+EXT (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/NSMethodSignature+EXT (0.4.1):
    - libextobjc/RuntimeExtensions
  - libextobjc/RuntimeExtensions (0.4.1)
  - libextobjc/UmbrellaHeader (0.4.1)
  - Lockbox (2.1.0)
  - Mantle (1.5.4):
    - Mantle/extobjc (= 1.5.4)
  - Mantle/extobjc (1.5.4)
  - Nimble (7.1.2)
  - OCMock (3.4.1)
  - OHHTTPStubs (4.1.0)
  - OptimizelySDKCore (2.1.0)
  - OptimizelySDKDatafileManager (2.1.0):
    - OptimizelySDKShared (= 2.1.0)
  - OptimizelySDKEventDispatcher (2.1.0):
    - OptimizelySDKShared (= 2.1.0)
  - OptimizelySDKiOS (2.1.0):
    - OptimizelySDKDatafileManager (= 2.1.0)
    - OptimizelySDKEventDispatcher (= 2.1.0)
    - OptimizelySDKUserProfileService (= 2.1.0)
  - OptimizelySDKShared (2.1.0):
    - OptimizelySDKCore (= 2.1.0)
  - OptimizelySDKUserProfileService (2.1.0):
    - OptimizelySDKShared (= 2.1.0)
  - Quick (1.3.0)
  - ReactiveCocoa (2.5):
    - ReactiveCocoa/UI (= 2.5)
  - ReactiveCocoa/Core (2.5):
    - ReactiveCocoa/no-arc
  - ReactiveCocoa/no-arc (2.5)
  - ReactiveCocoa/UI (2.5):
    - ReactiveCocoa/Core
  - RSSwizzle (0.1.0)
  - TOCropViewController (2.2)
  - UIColor+Hex (1.0.1):
    - UIColor+Hex/NSColor (= 1.0.1)
    - UIColor+Hex/UIColor (= 1.0.1)
  - UIColor+Hex/UIColor (1.0.1)
  - UICountingLabel (1.4.1)
  - UrbanAirship-iOS-AppExtensions (8.6.0)
  - UrbanAirship-iOS-SDK (8.6.0)

DEPENDENCIES:
  - AFNetworkActivityLogger (~> 2.0)
  - AFNetworking (~> 2.6.3)
  - Crashlytics (= 3.9.3)
  - Fabric (= 1.7.2)
  - GoogleTagManager (= 3.15.0)
  - libextobjc (~> 0.4)
  - Lockbox (~> 2.1.0)
  - Mantle (= 1.5.4)
  - Nimble (= 7.1.2)
  - OCMock (= 3.4.1)
  - OHHTTPStubs (= 4.1.0)
  - OptimizelySDKiOS (= 2.1.0)
  - Quick (= 1.3.0)
  - ReactiveCocoa (~> 2.0)
  - RSSwizzle (~> 0.1.0)
  - TOCropViewController (= 2.2)
  - UIColor+Hex
  - UICountingLabel (~> 1.4.0)
  - UrbanAirship-iOS-AppExtensions (= 8.6.0)
  - UrbanAirship-iOS-SDK (= 8.6.0)

**Comment by ryanwilson** [comment]
@Piramanayagamm can you please share your `Podfile.lock` as well so we can see what versions each pod resolved to? Thanks!

**Comment by paulb777** [comment]
We reproduced this yesterday and the fix will be in the Firebase 5.9.0. Internally tracked at b/116139404

Two possible workarounds:
- Use `use_frameworks!` in the Podfile
- Remove `-all_load` from the `Other Linker Flags` Build Setting
