### ISSUE TITLE
 Could not find or use auto-linked framework 'FBLPromises'

### ISSUE THREAD

**Issue by Zeus64** [firebase/firebase-ios-sdk#10533]
### Description

I'm using delphi to build my ios App. Starting with firebase 9, I cannot anymore compile my project with firebase. when I try (with -ObjC linker flag) i receive error like: 

```
[DCC Error] E2597 ld: warning: Could not find or use auto-linked framework 'FBLPromises'
  Undefined symbols for architecture arm64:
      Error: "_OBJC_CLASS_$_FIRHeartbeatController", referenced from:      objc-class-ref in ios-arm64/FirebaseCore.framework/FirebaseCore(FIRHeartbeatLogger.o);
```
and this still firebase 10.2.0. but with firebase 8.15.0 it's was working fine. Is there any change made in firebase 9.0.0 that can explain this? Is there any workaround? 

### Firebase SDK Version

9.0.0

### Xcode Version

delphi

### Installation Method

Zip

### Firebase Product(s)

Messaging

### Targeted Platforms

iOS

### Relevant Log Output

```shell
[DCC Error] E2597 ld: warning: Could not find or use auto-linked framework 'FBLPromises'
  Undefined symbols for architecture arm64:
      Error: "_OBJC_CLASS_$_FIRHeartbeatController", referenced from:      objc-class-ref in ios-arm64/FirebaseCore.framework/FirebaseCore(FIRHeartbeatLogger.o);
```

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
FIRHeartbeatController is defined in the module FirebaseCoreInternal that was introduced in Firebase 9.0.0

**Comment by Zeus64** [comment]
Thanks, what is FIRHeartbeatController and why it's can make the linking fail ?

**Comment by paulb777** [comment]
The FirebaseCore implementation now depends on FIRHeartbeatController, so FirebaseCoreInternal must be linked as well

**Comment by Zeus64** [comment]
No, adding FirebaseCore didn't help :( There is definitively something wrong in Firebase 9.0.0

to go a little further, when I add the linker option:
-ObjC

then i receive

[DCC Error] E2597 ld: warning: Could not find or use auto-linked framework 'GoogleDataTransport'

and when I add the linker option:
-force_load .\Firebase\FirebaseMessaging\GoogleDataTransport.xcframework\ios-arm64\GoogleDataTransport.framework

then i receive

[DCC Error] E2597 ld: can't open file, errno=13 for architecture arm64

when i do lipo -info GoogleDataTransport.framework/GoogleDataTransport

then i receive

Non-fat file: GoogleDataTransport.framework/GoogleDataTransport is architecture: arm64

so the framework is arm64, but the linker can not open it for an unknown reason

**Comment by paulb777** [comment]
If you can reproduce with one of the supported Firebase distributions, the Firebase team can investigate further.

Otherwise we can leave open if someone else in the community can help with the Delphi configuration.

**Comment by Zeus64** [comment]
thanks @paulb777 

I investigate a little more and now i have this :

```
  ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
  ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
  ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
  ld: warning: Could not find or use auto-linked framework 'DataDetection'
  ld: warning: Could not find or use auto-linked framework 'Combine'
  ld: warning: Could not find or use auto-linked framework 'Accessibility'
  ld: warning: Could not find or use auto-linked framework 'SwiftUI'
  ld: warning: Could not find or use auto-linked framework 'DeveloperToolsSupport'
  ld: warning: Could not find or use auto-linked framework 'UniformTypeIdentifiers'
  ld: warning: Could not find or use auto-linked framework 'CoreData'
  Undefined symbols for architecture arm64:
    Error: "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:      __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(_ObjC_HeartbeatController.o);      __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(_ObjC_HeartbeatsPayload.o);      __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(Heartbeat.o);      __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatController.o);      __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatsBundle.o);      __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatsPayload.o);      __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatStorage.o);      ...
       (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseCoreInternal, __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseAnalyticsSwift )
    Error: "_$s7SwiftUI4ViewMp", referenced from:      l_got.$s7SwiftUI4ViewMp in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI25_AppearanceActionModifierVAA04ViewE0AAWP", referenced from:      _$s7SwiftUI15ModifiedContentVyAA014_ViewModifier_D0Vy017FirebaseAnalyticsA006LoggedhF0VGAA017_AppearanceActionF0VGACyxq_GAA0E0A2aNRzAA0eF0R_rlWl in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierPAAE05_makeC08modifier6inputs4bodyAA01_C7OutputsVAA11_GraphValueVyxG_AA01_C6InputsVAiA01_J0V_ANtctFZ", referenced from:      _$s22FirebaseAnalyticsSwift06LoggedB8ModifierV0C2UI04ViewE0AadEP05_makeG08modifier6inputs4bodyAD01_G7OutputsVAD11_GraphValueVyxG_AD01_G6InputsVAlD01_M0V_AQtctFZTW in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:      __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(_ObjC_HeartbeatController.o);      __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(_ObjC_HeartbeatsPayload.o);      __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(Heartbeat.o);      __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatController.o);      __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatsBundle.o);      __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatsPayload.o);      __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal in ios-arm64/FirebaseCoreInternal.framework/FirebaseCoreInternal(HeartbeatStorage.o);      ...
       (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseCoreInternal, __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseAnalyticsSwift )
    Error: "_$s7SwiftUI12ViewModifierP4body7content4BodyQzAA01_cD8_ContentVyxG_tFTq", referenced from:      l_got.$s7SwiftUI12ViewModifierP4body7content4BodyQzAA01_cD8_ContentVyxG_tFTq in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierPAAE05_makeC4List8modifier6inputs4bodyAA01_cF7OutputsVAA11_GraphValueVyxG_AA01_cF6InputsVAiA01_K0V_ANtctFZ", referenced from:      _$s22FirebaseAnalyticsSwift06LoggedB8ModifierV0C2UI04ViewE0AadEP05_makeG4List8modifier6inputs4bodyAD01_gI7OutputsVAD11_GraphValueVyxG_AD01_gI6InputsVAlD01_N0V_AQtctFZTW in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s4Body7SwiftUI12ViewModifierPTl", referenced from:      l_got.$s4Body7SwiftUI12ViewModifierPTl in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:      __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FirebaseAnalyticsSwift in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
       (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FirebaseAnalyticsSwift)
    Error: "_$s7SwiftUI21_ViewModifier_ContentVMn", referenced from:      _symbolic _____y_____y_____G_____G 7SwiftUI15ModifiedContentV AA014_ViewModifier_D0V 017FirebaseAnalyticsA006LoggedhF0V AA017_AppearanceActionF0V in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);      _symbolic _____y_____G 7SwiftUI21_ViewModifier_ContentV 017FirebaseAnalyticsA006LoggedgD0V in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierPAAE14_viewListCount6inputs4bodySiSgAA01_cfG6InputsV_AgIXEtFZ", referenced from:      _$s22FirebaseAnalyticsSwift06LoggedB8ModifierV0C2UI04ViewE0AadEP14_viewListCount6inputs4bodySiSgAD01_giJ6InputsV_AjLXEtFZTW in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI25_AppearanceActionModifierVMn", referenced from:      _symbolic _____y_____y_____G_____G 7SwiftUI15ModifiedContentV AA014_ViewModifier_D0V 017FirebaseAnalyticsA006LoggedhF0V AA017_AppearanceActionF0V in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI4ViewPAAE8modifieryAA15ModifiedContentVyxqd__Gqd__lF", referenced from:      _$s7SwiftUI4ViewP017FirebaseAnalyticsA0E15analyticsScreen4name5class15extraParametersQrSS_SSSDySSypGtF in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI15ModifiedContentVyxq_GAA4ViewA2aERzAA0E8ModifierR_rlMc", referenced from:      l_get_witness_table 7SwiftUI4ViewRzlAA15ModifiedContentVyx017FirebaseAnalyticsA006LoggedG8ModifierVGAaBHPxAaBHD1__AgA0cI0HPyHCHC in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);      _$s7SwiftUI15ModifiedContentVyAA014_ViewModifier_D0Vy017FirebaseAnalyticsA006LoggedhF0VGAA017_AppearanceActionF0VGACyxq_GAA0E0A2aNRzAA0eF0R_rlWl in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierMp", referenced from:      l_got.$s7SwiftUI12ViewModifierMp in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI15ModifiedContentVMa", referenced from:      l_get_witness_table 7SwiftUI4ViewRzlAA15ModifiedContentVyx017FirebaseAnalyticsA006LoggedG8ModifierVGAaBHPxAaBHD1__AgA0cI0HPyHCHC in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);      _$s7SwiftUI15ModifiedContentVyAA014_ViewModifier_D0Vy017FirebaseAnalyticsA006LoggedhF0VGAA017_AppearanceActionF0VGMa in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_swift_getOpaqueTypeConformance", referenced from:      _$s22FirebaseAnalyticsSwift06LoggedB8ModifierV0C2UI04ViewE0AA4BodyAdEP_AD0G0PWT in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI25_AppearanceActionModifierVN", referenced from:      _$s7SwiftUI15ModifiedContentVyAA014_ViewModifier_D0Vy017FirebaseAnalyticsA006LoggedhF0VGAA017_AppearanceActionF0VGMa in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI21_ViewModifier_ContentVMa", referenced from:      _$s7SwiftUI21_ViewModifier_ContentVy017FirebaseAnalyticsA006LoggedgD0VGMa in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI15ModifiedContentVMn", referenced from:      _symbolic _____yx_____G 7SwiftUI15ModifiedContentV 017FirebaseAnalyticsA006LoggedF8ModifierV in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);      _symbolic _____y_____y_____G_____G 7SwiftUI15ModifiedContentV AA014_ViewModifier_D0V 017FirebaseAnalyticsA006LoggedhF0V AA017_AppearanceActionF0V in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI21_ViewModifier_ContentVyxGAA0C0AAMc", referenced from:      _$s7SwiftUI21_ViewModifier_ContentVy017FirebaseAnalyticsA006LoggedgD0VGACyxGAA0C0AAWl in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierP4BodyAC_AA0C0Tn", referenced from:      l_got.$s7SwiftUI12ViewModifierP4BodyAC_AA0C0Tn in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierP05_makeC08modifier6inputs4bodyAA01_C7OutputsVAA11_GraphValueVyxG_AA01_C6InputsVAiA01_J0V_ANtctFZTq", referenced from:      l_got.$s7SwiftUI12ViewModifierP05_makeC08modifier6inputs4bodyAA01_C7OutputsVAA11_GraphValueVyxG_AA01_C6InputsVAiA01_J0V_ANtctFZTq in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierP05_makeC4List8modifier6inputs4bodyAA01_cF7OutputsVAA11_GraphValueVyxG_AA01_cF6InputsVAiA01_K0V_ANtctFZTq", referenced from:      l_got.$s7SwiftUI12ViewModifierP05_makeC4List8modifier6inputs4bodyAA01_cF7OutputsVAA11_GraphValueVyxG_AA01_cF6InputsVAiA01_K0V_ANtctFZTq in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_$s7SwiftUI12ViewModifierP14_viewListCount6inputs4bodySiSgAA01_cfG6InputsV_AgIXEtFZTq", referenced from:      l_got.$s7SwiftUI12ViewModifierP14_viewListCount6inputs4bodySiSgAA01_cfG6InputsV_AgIXEtFZTq in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
    Error: "_OBJC_CLASS_$_FIRAnalytics", referenced from:      objc-class-ref in ios-arm64/FirebaseAnalyticsSwift.framework/FirebaseAnalyticsSwift(Analytics+SwiftUI.o);
       (maybe you meant: _OBJC_CLASS_$_FIRAnalyticsConfiguration)
  ld: symbol(s) not found for architecture arm64
```

do you know what's it's mean exactly ?

**Comment by paulb777** [comment]
One issue may be that the Swift library is not being linked. A workaround for that is to add a dummy swift source file to the project.

**Comment by Zeus64** [comment]
thanks @paulb777 , do you know how to link the swift library ? I'm not under xcode so I cannot add a dummy swift source file, I need to link it manually. why it's was working in 8.15.0 but not anymore in 9.0.0+ ?

**Comment by paulb777** [comment]
Firebase 9.0.0 is the first version of Firebase that includes required Swift implementation sources.

**Comment by Zeus64** [comment]
thanks @paulb777 now that explain why it's not working under 9.0.0. do you know where I can found this swiftFileProvider library? I look everywhere and I can't find it :(

**Comment by Zeus64** [comment]
Ok if someone come one day here, this is the procedure to make it working under Delphi :

Ok, i made it working with the very last version of firebird (10.2.0) like this :

Under Tools, Options, SDK Manager you will need to add the following frameworks for ios64 and Ios64 simulator:

Path on remote machine                                                                  |  File mask               |  Path Type     |  Include subdirectories
- $(SDKROOT)/usr/lib/swift                                                              |  *                       |  Library path  |  no
- $(SDKROOT)/../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos  |  *                       |  Library path  |  no

Still [this bug report](https://quality.embarcadero.com/browse/RSP-38700) is not yet corrected you will need to manually copy the content of (assuming c:\SDKs is your SDK root home) c:\SDKs\iPhoneOS16.1.sdk\Applications\Xcode.app\Contents\Developer\Toolchains\XcodeDefault.xctoolchain\usr\lib\swift\iphoneos\
to c:\SDKs\iPhoneOS16.1.sdk\usr\lib\swift\ and then you can delete the folder c:\SDKs\iPhoneOS16.1.sdk\Applications\

after this you need to add in the code :

procedure ClangRTLoader; cdecl; external '/usr/lib/clang/lib/darwin/libclang_rt.ios.a';
procedure FirebaseCoreInternalLoader; cdecl; external framework 'FirebaseCoreInternal';
procedure FirebaseCoreLoader; cdecl; external framework 'FirebaseCore';
procedure libswiftCompatibility50Loader; cdecl; external '/usr/lib/swift/libswiftCompatibility50.a';
procedure libswiftCompatibility51Loader; cdecl; external '/usr/lib/swift/libswiftCompatibility51.a';
procedure libswiftCompatibilityConcurrencyLoader; cdecl; external '/usr/lib/swift/libswiftCompatibilityConcurrency.a';
procedure libswiftCompatibilityDynamicReplacementsLoader; cdecl; external '/usr/lib/swift/libswiftCompatibilityDynamicReplacements.a';
procedure libswiftCoreFoundationLoader; cdecl; external '/usr/lib/swift/libswiftCoreFoundation.dylib';
procedure libswiftCoreImageLoader; cdecl; external '/usr/lib/swift/libswiftCoreImage.dylib';
procedure libswiftCoreLoader; cdecl; external '/usr/lib/swift/libswiftCore.dylib';
procedure libswiftDarwinLoader; cdecl; external '/usr/lib/swift/libswiftDarwin.dylib';
procedure libswiftDataDetectionLoader; cdecl; external '/usr/lib/swift/libswiftDataDetection.dylib';
procedure libswiftDispatchLoader; cdecl; external '/usr/lib/swift/libswiftDispatch.dylib';
procedure libswiftFileProviderLoader; cdecl; external '/usr/lib/swift/libswiftFileProvider.dylib';
procedure libswiftMetalLoader; cdecl; external '/usr/lib/swift/libswiftMetal.dylib';
procedure libswiftObjectiveCLoader; cdecl; external '/usr/lib/swift/libswiftObjectiveC.dylib';
procedure libswiftQuartzCoreLoader; cdecl; external '/usr/lib/swift/libswiftQuartzCore.dylib';
procedure libswiftUIKitLoader; cdecl; external '/usr/lib/swift/libswiftUIKit.dylib';

and then you can sucessfully compile the firebase 10.2.0

**Comment by paulb777** [comment]
Thanks for sharing the solution @Zeus64 👍
