### ISSUE TITLE
Carthage Firebase 6.6 reports error Unable to find module header

### ISSUE THREAD

**Issue by possen** [firebase/firebase-ios-sdk#3578]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.3
  * Firebase SDK version: 6.6
  * Firebase Component: Firebase 
  * Component version: 6.6

#### Steps to reproduce:

carthage update --platform iOS 
upgrades to 6.6, I had to revert to 6.5 by forcing the Cartfile to point to "== 6.5"

error occurs when building my project in Xcode:

/Users/user/Projects/Dem/Carthage/Build/iOS/Firebase.framework/Modules/module.modulemap:3:10: warning: skipping 'Firebase.h' because module declaration of 'Firebase' lacks the 'framework' qualifier
  header "Firebase.h"
         ^
/Users/user/Projects/Dem/Carthage/Build/iOS/Firebase.framework/Modules/module.modulemap:1:1: note: use 'framework module' to declare module 'Firebase'
module Firebase {
^
/Users/user/Projects/Dem/Carthage/Build/iOS/Firebase.framework/Modules/module.modulemap:3:10: warning: skipping 'Firebase.h' because module declaration of 'Firebase' lacks the 'framework' qualifier
  header "Firebase.h"
         ^
/Users/user/Projects/Dem/Carthage/Build/iOS/Firebase.framework/Modules/module.modulemap:1:1: note: use 'framework module' to declare module 'Firebase'
module Firebase {
^
/Users/user/Projects/Dem/Carthage/Build/iOS/Firebase.framework/Modules/module.modulemap:3:10: error: header 'Firebase.h' not found
  header "Firebase.h"
         ^
<unknown>:0: error: could not build Objective-C module 'Firebase'

**Comment by paulb777** [comment]
@possen Thanks for the report.  We'll take a look.

 Another workaround would likely be to copy the 6.5.0 Firebase.framework to a 6.6.0 installation.

**Comment by petrovi4** [comment]
I have the same problem ((

**Comment by ryanwilson** [comment]
Sorry about the trouble! I'll try to get a fix up early tomorrow for this.

**Comment by RustyKnight** [comment]
Had this issue (all of sudden and unexpectedly), took some time to figure out what the probable cause might be.

I simply restricted Carthage to only using version 6.5.0

`binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.5.0`

not sure if it work for all the libraries, but the ones I'm using worked find

**Comment by petrovi4** [comment]
> I simply restricted Carthage to only using version 6.5.0

It's a good, though temporary, solution. 
Well, we're waiting for an update from the project maintainers.

**Comment by paulb777** [comment]
The problem is that Firebase module definition at `Carthage/Build/iOS/Firebase.framework/Modules/module.modulemap` is missing the `framework` specifier. 

The simplest workaround is to edit the file to include it:

```
framework module Firebase {
  export *
  header "Firebase.h"
}
```

We'll look into posting a 6.6.1 version of FirebaseAnalyticsBinary with the fix.

**Comment by dhaneshgosai** [comment]
Thanks @paulb777.

Its working fine now.

**Comment by petrovi4** [comment]
> Its working fine now.

Anyone who reads this and thinks it should work as planned now. Nothing like that. This works if you make changes to module.modulemap, but version 6.6.1 is still not released.

**Comment by paulb777** [comment]
@petrovi4 Yep, sorry it doesn't look like we'll get a 6.6.1 in. Instead we expect the module.modulemap fix to occur in this week's 6.7.0.

**Comment by kkendall33** [comment]
> I have the same problem ((
> 
> When I manually download Firebase.framework version 6.5.0 and replace this file, the compilation stops with an error
> 
> ```
> ld: warning: Could not find auto-linked framework 'Firebase'
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_GDTTransport", referenced from:
>       objc-class-ref in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Similarly, if I replace all the files from Analytics-fe0669fafb68cf16.zip

How did you fix this issue? My CartFile has like this: `binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 6.5.0` and after `carthage update` I still have this issue.

**Comment by paulb777** [comment]
@kkendall33 If the 6.6.0 FirebaseCoreDiagnostics.framework is included, also include the 6.6.0 GoogleDataTransport.framework.

**Comment by kkendall33** [comment]
> @kkendall33 If the 6.6.0 FirebaseCoreDiagnostics.framework is included, also include the 6.6.0 GoogleDataTransport.framework.

Could you help me find the right path for that? I'm assuming you mean include it with Carthage?

**Comment by paulb777** [comment]
It's in the Analytics folder of the Carthage distribution.

**Comment by Tr736** [comment]
do we have a working solution yet peeps? still running into the issue  and my CI is freaking out :(

**Comment by paulb777** [comment]
Sorry, we're transitioning to [improved tooling](https://github.com/firebase/firebase-ios-sdk/tree/master/ZipBuilder) that will make the Carthage generation and publishing more reliable in the long run.  However, going through a few hiccups in getting it right. We expect to get Carthage 6.7.0 out in the next day or two.

**Comment by ryanwilson** [comment]
Apologies for the delay - Firebase 6.7.0 is now available on Carthage and should include the updated modulemap. Please re-open this issue if you're still seeing the bug after updating to 6.7.0! Thanks for everyone's patience while we transition our tooling.

**Comment by rowanmulder** [comment]
When using the **_manual zip file_** to upgrade Firebase 6.5.0 to 6.7.0 the same errors occurs in Xcode, this was also the case in 6.6.0 as mentioned before in this ticket:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GDTTransport", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
  "_GDTLog", referenced from:
      -[FIRCoreDiagnosticsLog transportBytes] in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
      _FIRPopulateProtoWithCommonInfoFromApp in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ValCanBuild** [comment]
Still seeing this too. Updated using carhage 6.5.0 -> 6.7.0

**Comment by ryanwilson** [comment]
@rowanmulder @ValCanBuild are you seeing the modulemap issue still, or just the `Unidentified symbols` issue?

**Comment by paulb777** [comment]
The 6.7.0 zip (and Carthage distribution) include additional frameworks in the Analytics folder. Make sure that all of the additions get added to the project.

**Comment by mariancerny** [comment]
I had the same problem with undefined symbols `GDTTransport` and `GDTLog`.
I have solved the problem by adding the two new frameworks `GoogleDataTransport.framework` and `GoogleDataTransportCCTSupport.framework` in `Carthage/Build/iOS directory` to the project.

I also had an additional error:
`error: Carthage/Build/iOS/FirebaseFirestore.framework/gRPCCertificates-Cpp.bundle: No such file or directory`
The bundle has been moved from `FirebaseFirestore.framework` to `gRPC-C++.framework`.

**Comment by ValCanBuild** [comment]
Thanks @mariancerny that helped. Adding `GoogleDataTransport.framework` was enough to fix it for me (I only use Firebase for auth)

**Comment by rowanmulder** [comment]
@ryanwilson Sorry my bad, I was missing the new libraries when building the project. I've added the ones @mariancerny (thx!) mentioned for Google Data Transport.

Maybe we can make the documentation more clear for upgrades when libraries get renamed/deleted/added, eg. add it to the release notes or readme.md?

**Comment by hixfield** [comment]
@rowanmulder the doc still talk about copying the gRPCCertificates-Cpp.bundle out of the FirebaseFirestore.framework but its moved to the gRPC-C++.framework as mentioned by @mariancerny we should update the documentation.

**Comment by RanjeetStiga** [comment]
> I had the same problem with undefined symbols `GDTTransport` and `GDTLog`.
> I have solved the problem by adding the two new frameworks `GoogleDataTransport.framework` and `GoogleDataTransportCCTSupport.framework` in `Carthage/Build/iOS directory` to the project.
> 
> I also had an additional error:
> `error: Carthage/Build/iOS/FirebaseFirestore.framework/gRPCCertificates-Cpp.bundle: No such file or directory`
> The bundle has been moved from `FirebaseFirestore.framework` to `gRPC-C++.framework`.
> (The documentation at https://github.com/firebase/firebase-ios-sdk/blob/master/Carthage.md contains the old path.)

How to Add GoogleDataTransport.framework and GoogleDataTransportCCTSupport.framework ?

**Comment by paulb777** [comment]
@RanjeetStiga Both GoogleDataTransport.framework and GoogleDataTransportCCTSupport.framework are in the Analytics folder.

**Comment by animeshd** [comment]
This problem is still not fixed in latest release, 6.8.1.

**Comment by RanjeetStiga** [comment]
> @RanjeetStiga Both GoogleDataTransport.framework and GoogleDataTransportCCTSupport.framework are in the Analytics folder.

Thanks it's work .

**Comment by shahabafridi85** [comment]
I have have the same problem 

I manually download Firebase.framework version 6.1.0 and Crashlytics 3.14.0
Now when I replaced the framework files while updating from 6.1.0 -> 6.9.0

ld: warning: directory not found for option '-F/Users/MyUser/MyCompany/MyApp/Frameworks'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GDTCORTransport", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
  "_GDTCORLog", referenced from:
      -[FIRCoreDiagnosticsLog transportBytes] in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
      _FIRPopulateProtoWithCommonInfoFromApp in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

As suggested by @paulb777 I added the following two frameworks:
GoogleDataTransport.framework and GoogleDataTransportCCTSupport.framework

Now if I debug application on devices that already have my application, it does not stop on breakpoints.

For installing on new devices it gives error:

**Could not locate installed application**
_Install claimed to have succeeded, but application could not be found on device. bundleId = com.XXX.XXXXXXXX_

If i run it on simulator it gives error"
**This app could not be installed at this time.**
_Could not install at this time.
Failed to load Info.plist from bundle at path /Users/myUser/Library/Developer/CoreSimulator/Devices/B9775552-65FA-4C1E-8051-06922702A4BC/data/Library/Caches/com.apple.mobile.installd.staging/temp.eJW69a/extracted/Payload/MyApp.app/Frameworks/GoogleDataTransport.framework_

**Comment by paulb777** [comment]
@shahabafridi85 Likely you have a mix of Firebase frameworks from different releases. 

I'd recommend removing all of them and installing only from 6.9.0

**Comment by annca** [comment]
I'm experiencing the same issue as @shahabafridi85. I downloaded the SDK and added it to the project manually. I deleted the previous files from my project and added what was newly downloaded, so there's no mix. Can't install on neither the simulator nor device. Seeing exact same errors. Any other suggestions?

**Comment by shahabafridi85** [comment]
@annca Yes I did resolved the issue. 
Thanks @paulb777 for your suggestion. The issue was not because fo  the mix of Firebase frameworks from different releases.

Before I was adding the frameworks by adding the plus (+) on the Embedded Framework section in the Target. 
The issue was resolved by deleting the frameworks from old release and then adding the new release frameworks by dragging and dropping in the Project Navigator.

I hope it help you.

**Comment by annca** [comment]
Ah got it. Confirming that this helped me resolve the issue as well. Thanks!!!

**Comment by ahmeric** [comment]
I have the same error, 
```
ld: warning: Could not find auto-linked framework 'Firebase'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GDTCORTransport", referenced from:
      objc-class-ref in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
  "_GDTCORLog", referenced from:
      -[FIRCoreDiagnosticsLog transportBytes] in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
      _FIRPopulateProtoWithCommonInfoFromApp in FirebaseCoreDiagnostics(FIRCoreDiagnostics.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
And not able to solve by any suggested methods. It takes all day. Still it stucks.

**Comment by paulb777** [comment]
@ahmeric It looks like the GoogleDataTransport.framework is missing or it's an old version.

**Comment by possen** [comment]
As the original poster, I just wanted to confirm that I was able to upgrade to 6.9.0, by removing the == 6.5 from the Cartfile. Thank you.

**Comment by ahmeric** [comment]
Thanks, @paulb777 it has solved my problem. But until today, it was working without adding this framework to the linked libraries.

**Comment by cambronjay** [comment]
I am still experiencing this issue. Any viable solution?
