### PR TITLE
Add missing new header to Firestore podspec

### PR DESCRIPTION
**Pull request by paulb777**
Fix `pod spec lint` failure introduced in #7717 and caught in nightly #7726.

`- NOTE | xcodebuild: FirebaseFirestore/Firestore/core/src/bundle/bundle_serializer.h:33:10: fatal error: 'Firestore/third_party/nlohmann_json/json.hpp' file not found`

### CODE REVIEW

**Review by var-const — APPROVED** [review]

**Comment by paulb777** [comment]
The test still failed since it looks like the prerelease workflow uses master and not the PR from the podspec.  I'll merge, since it should fix, and the release process will validate.
