### ISSUE TITLE
SPM - Undefined symbol: _OBJC_CLASS_$_FIRAnalytics

### ISSUE THREAD

**Issue by cschelly** [firebase/firebase-ios-sdk#6518]
Hello,

When trying to install `FirebaseAnalytics` package via SPM version 6.33-spm-beta, I receive the following error:

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRAnalytics", referenced from:
      objc-class-ref in [REDACTED].o
     (maybe you meant: _OBJC_CLASS_$_FIRAnalyticsConfiguration)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I am importing `FirebaseCore` and `FirebaseAnalytics` within my project (`FirebaseCore` because I am setting the `FirebaseLoggerLevel`)

I have indeed added the `-ObjC` flag to the `Other Linker Flags` setting and done a deep clean, deleted derived data, etc.

Would you please be able to advise?

Thank you!

EDIT: I am using Xcode 12 as well, thanks

**Comment by paulb777** [comment]
@cschelly Thanks for the report. This looks like an incarnation of #6425.  

Do you see any difference between the `6.33-spm-beta` and `6.32-spm-beta` branches?

We haven't yet been able to reproduce this and would appreciate a reproducible example.

**Comment by cschelly** [comment]
Thanks for the quick response, @paulb777! 

I had already come across #6425 and that is when I upgraded from 6.32 to 6.33 with no luck. But, I couldn't repro the issue with a stripped down project. So, I created a brand new project and everything works fine. Hopefully, that will help anyone else that might see this error message. 

For more context, I was using Carthage before switching to SPM and there may have been some artifacts causing problems. My project was really small and it wasn't a big deal to create a new one, so looking into the Carthage/SPM transition might be worth more investigation for anyone else.

Thanks again!
