### ISSUE TITLE
Duplicate symbol _FirebaseCoreVersionString for architecture arm64 when using SDK version 5.0.0 via Cocoapods 

### ISSUE THREAD

**Issue by averello** [firebase/firebase-ios-sdk#1257]
# Evironment

  * Xcode version: Version 9.3 (9E145)
  * Firebase SDK version: 5.0.0
  * Firebase Component: Core
  * Component version: 5.0.0

# Problem

#### Steps to reproduce:

Can not reproduce in a clean/simple project that contains only Firebase/Core as its cocoa pod dependency.

1. Pod install
2. Archive
3. Error

#### Error Code:

```
duplicate symbol _FirebaseCoreVersionString in:
    /Users/user/Library/Developer/Xcode/DerivedData/Target-dowlcsklsjexzzgbaaufnfpvjeqd/Build/Intermediates.noindex/ArchiveIntermediates/Target/BuildProductsPath/Release-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIRVersion.o)
    /Users/user/Library/Developer/Xcode/DerivedData/Target-dowlcsklsjexzzgbaaufnfpvjeqd/Build/Intermediates.noindex/ArchiveIntermediates/Target/BuildProductsPath/Release-iphoneos/FirebaseCore/FirebaseCore.framework/FirebaseCore(FirebaseCore_vers.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Discussion
Tried to delete `~/Library/Developer/Xcode/DerivedData/` but the error perseveres.
`Firebase/Core 4.0.20` part of `Firebase 4.13.0` works as intended.

**Comment by paulb777** [comment]
@averello This looks like a known issue that the fix will go out in the next patch.  (Unfortunately a documentation glitch is currently showing the 5.0.0 known issues in the 4.13.0 section of the[ release notes](https://firebase.google.com/support/release-notes/ios).) 

The fix (and workaround) is visible at #1223.

Note, that we've only seen this issue when the -all_load option is set in `Other Linker Flags`. Is that the case for you?

**Comment by xaphod** [comment]
+1. I just got this too when I updated from cocoapods 1.4.0 to 1.5.2. Earlier in the day I went from Firebase 4.x to 5.0 just fine, but then cocoapods 1.5.2 seems to break Firebase.

```
duplicate symbol _FirebaseCoreVersionString in:
    /Users/Tim/Library/Developer/Xcode/DerivedData/Photobooth-carrpjksdzfewpftlvqzuglaxplu/Build/Products/Debug-iphonesimulator/FirebaseCore/FirebaseCore.framework/FirebaseCore(FIRVersion.o)
    /Users/Tim/Library/Developer/Xcode/DerivedData/Photobooth-carrpjksdzfewpftlvqzuglaxplu/Build/Products/Debug-iphonesimulator/FirebaseCore/FirebaseCore.framework/FirebaseCore(FirebaseCore_vers.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by xaphod** [comment]
UPDATE: per the answer here, `-all_load` is no longer needed (since XCode 4.2 it seems!) if you're using `-ObjC`. https://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library/2615407#2615407

I removed it from the libs that needed it, and those libs appear to still be working fine. So far (caveat emptor)

**Comment by paulb777** [comment]
@xaphod Thanks for the confirmation! I'll close this now since the fix is on the way for the next release.
