### ISSUE TITLE
No such module 'GTMSessionFetcherCore'

### ISSUE THREAD

**Issue by chtnsngh** [firebase/firebase-ios-sdk#11561]
### Description

Compilation error in FirebaseStorage pod, version - 10.10.0
<img width="963" alt="Screenshot 2023-07-18 at 12 10 39 AM" src="https://github.com/firebase/firebase-ios-sdk/assets/70207147/1315f60b-3ce4-4a30-8f98-ff700b724214">

### Reproducing the issue

After upgrading from 9.6 to 10.10 version, getting compilation errors in FirebaseStorage pod wherever 'COCOAPODS' macro is used. In pods project the 'COCOAPODS=1' MACRO is already defined.

### Firebase SDK Version

10.10.0

### Xcode Version

14.1

### Installation Method

CocoaPods

### Firebase Product(s)

Storage

### Targeted Platforms

iOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment]
We'll likely need a reproducible example to help, since there is likely something corrupt in the project undefining the `COCOAPODS` macro.

**Comment by chtnsngh** [comment]
Wrong configuration leading to COCOAPODS macro overriding
